### ISSUE TITLE
wamp.registration.list broken in 0.11.2

### ISSUE THREAD

**Issue by stopthatcow** [crossbario/crossbar#562] opened 2015-12-22 00:56 UTC
after upgrading to 0.11.2 I get the following exception thrown when calling "wamp.registration.list":

(env) C:>crossbar start --cbdir=config\domain1\config
←[34m2015-12-21T16:46:58-0800 [Controller  18300]←[39m ←[33m←[1m     __  __  __  __  __  __      __     __←[0m
←[34m2015-12-21T16:46:58-0800 [Controller  18300]←[39m ←[33m←[1m    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \←[0m
←[34m2015-12-21T16:46:58-0800 [Controller  18300]←[39m ←[33m←[1m    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/←[0m
←[34m2015-12-21T16:46:58-0800 [Controller  18300]←[39m ←[33m←[1m                                        ←[0m
←[34m2015-12-21T16:46:58-0800 [Controller  18300]←[39m     Version: ←[33m←[1m0.11.2←[0m
←[34m2015-12-21T16:46:58-0800 [Controller  18300]←[39m
←[34m2015-12-21T16:46:58-0800 [Controller  18300]←[39m Starting from node directory C:\config\domain1\config
←[34m2015-12-21T16:46:59-0800 [Controller  18300]←[39m Loading node configuration file 'C:\config\domain1\config\config.json'
←[34m2015-12-21T16:46:59-0800 [Controller  18300]←[39m Entering reactor event loop...
←[31m2015-12-21T16:46:59-0800 [Controller  18300]←[39m Warning, could not set process title (setproctitle not installed)
←[34m2015-12-21T16:46:59-0800 [Controller  18300]←[39m Joined realm 'crossbar' on node management router
←[34m2015-12-21T16:46:59-0800 [Controller  18300]←[39m No WAMPlets detected in enviroment.
←[34m2015-12-21T16:46:59-0800 [Controller  18300]←[39m Starting Router with ID 'worker1'...
←[33m2015-12-21T16:46:59-0800 [Router      13316]←[39m Worker running under CPython-IOCPReactor
←[34m2015-12-21T16:47:00-0800 [Controller  18300]←[39m Router with ID 'worker1' and PID 13316 started
←[34m2015-12-21T16:47:00-0800 [Controller  18300]←[39m Router 'worker1': realm 'realm1' (named 'default') started
←[34m2015-12-21T16:47:00-0800 [Controller  18300]←[39m Router 'worker1': role 'role1' (named 'anonymous') started on realm 'realm1'
←[34m2015-12-21T16:47:00-0800 [Controller  18300]←[39m Router 'worker1': transport 'transport1' started
←[33m2015-12-21T16:47:00-0800 [Router      13316]←[39m Site starting on 8090
←[34m2015-12-21T16:47:00-0800 [Controller  18300]←[39m Router 'worker1': transport 'transport2' started
←[33m2015-12-21T16:47:00-0800 [Router      13316]←[39m WampRawSocketServerFactory starting on 8000
←[31m2015-12-21T16:47:21-0800 [Router      13316]←[39m AttributeError: 'WildcardTrieMatcher' object has no attribute 'values': Traceback (most recent call last):
  File "C:\env\lib\site-packages\crossbar\router\dealer.py", line 419, in on_authorize_success
    callee._transport.send(invocation)
  File "C:\env\lib\site-packages\crossbar\router\session.py", line 208, in send
    self._session.onMessage(msg)
  File "C:\env\lib\site-packages\autobahn\wamp\protocol.py", line 590, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "C:\env\lib\site-packages\txaio\tx.py", line 338, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "C:\env\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "C:\env\lib\site-packages\crossbar\router\service.py", line 306, in registration_list
    for registration in registration_map._observations_wildcard.values():
exceptions.AttributeError: 'WildcardTrieMatcher' object has no attribute 'values'

this doesn't occur in Crossbar 0.11.0

**Comment by oberstet** [comment] 2015-12-24 19:11
duplicate of https://github.com/crossbario/crossbar/issues/565

**Closed by oberstet** 2015-12-24 19:11 UTC
