### ISSUE TITLE
One big call is holding all others

### ISSUE THREAD

**Issue by Tsunami2069** [crossbario/crossbar#741] opened 2016-04-27 14:45 UTC
Hello.

This is not really an issue but more of a question as to whether this is normal behaviour or something we might have done wrong on our part.

We have a Crossbar WAMP router running on one of our applications. This router is responsible registering a series of procedures (in PHP files) that will handle the database requests. These procedures are called by the web application.

So far, we've never noticed any issues with concurrent calls but recently, on one of the web applications new module, we have to do a rather massive import from an external service.
This import does a CURL call to the refered external service and, depending on the amount of time we specify, pulls a possibly large amount of information. Then the procedure registered on the WAMP runs through each of the returned lines and for each of them, runs a series of database queries. Depending on how big the amount of time, this procedure can run from 2 to 5, 10 minutes, again depending on the size.

The issue is that we've noticed that while this single call and procedure is running, no other calls are executed.
For example, while we are doing one big import, we try to simply open another module on the web application, this module does a simple call for a list (which is a simple query) but until the import finishes, the WAMP router doesn't return anything.
Upon completion of the import, ONLY THEN the new call is executed and the list is loaded.
We have tried it both localy and externally. And also by different computers / systems. Behaviour is identical.

I would like to ask your help in realizing if this is normal behaviour or could we did something wrong, maybe in the settings or... something else.
As it is right now, it appears that our router cannot handle multiple calls. It seems that it only accepts calls on a kind of "waiting in line" fashion.

Thank you very much for your help.

**Comment by goeddea** [comment] 2016-04-27 15:09
This is not expected behavior. Calls are independent of each other. The only blocking a long-running call should be able to do is within the callee if this runs synchronously. My first guess would be that the Web application you are calling is blocking until the expensive call has processed. What happens if you call a completely separate component during the execution of the expensive call? If you get blocking then please try to boil this down to a simple, reproducible example and file an issue based on that.

Until then: Questions are best handled on the mailing list - https://groups.google.com/forum/#!forum/crossbario.

Closing for now (but re-open or file a new issue if you can come back with something more definite!)

**Closed by goeddea** 2016-04-27 15:09 UTC

**Comment by oberstet** [comment] 2016-04-27 15:45
When I get this right, the WAMP component is written in a) PHP (Thruway?) and b) doing database stuff and c) using curl from PHP.

a) please ask the Thruway guys.
b) + c) both of these may block the event loop in Thruway (Ratchet)

All of this isn't related to Crossbar.io

**Comment by Tsunami2069** [comment] 2016-04-27 18:01
Hello. 

First of all, thank for your answers.

However, we've been "cracking" our heads on this issue and, having not yet obtained any positive results and also after reading your comments that this could be related to PHP and Thruway, we decided to make another test.

This new test was done using your Crossbar Python "hello world" test.

We had this test running and made a small change.
We changed the add2 function to make a giant for loop so that it would last, something like, 10 to 20 seconds.
We also added a new function called add3 that would just return some static text.

We then changed the index.html to only call the add2 function once and we created another html page (index2.html) that calls add3 function once.

We then proceed to open index.html page so that it would call the add2 function and its loop. While that loop was running, we opened the index2.html page so it would call add3 function and the conclusion was the same, The add3 function would not output the static text until the add2 function's loop and RPC was not complete.

Again, i'd like to point out that this was done using not the PHP but the python hello world example / demo.

If necessary, we can provide with this example we used since its a lot smaller.

Thank you once more for all the help.

**Comment by DZabavchik** [comment] 2016-04-27 18:57
Had a similar issue calling a web service from dynamic authenticator.  Not sure if this is a best approach but it resolves the problem.  Added a timeout and return `Deferred` from using `deferToThread`

```Python
def authenticate_connection_worker(authid, realm, details):
    # Expect to return dictionary:
    # {
    #    'authid': 'dot.separated.assigned.authid'  # assign a different auth ID during authentication
    #    'secret': '<SECRET>',
    #    'role': '<ROLE_NAME>'
    # }
    resp = requests.post('auth.service.host.pri/connect/authenticate'), json={
        'authid': authid,
        'realm': realm,
        'details': details
    }, timeout=5.)

    if resp.status_code != 200:
        raise ApplicationError(u'com.ninjamsp.no_such_user',
                               'could not authenticate session for user {} {}'
                               .format(authid, resp.status_code))
    else:
        return resp.json()

# Called from dynamic authenticator
def authenticate_connection(authid, realm, details):
    d = deferToThread(authenticate_connection_worker, authid, realm, details)
    return d
```

**Comment by Tsunami2069** [comment] 2016-04-27 19:06
Made another small test.

Added a sleep for 5 seconds after each of the add2 loops ran.
Wanted to see if all 3 calls would run for the 5 seconds (concurrently) or sequentially (15 seconds).
The result was 15 seconds, meaning they ran sequentially.

Im also attaching the complete python example.

Also, since i was not the one that closed this issue, i cannot re-open. Should i make a new one?

[PythonExample.zip](https://github.com/crossbario/crossbar/files/239223/PythonExample.zip)

Thank you once more.

**Comment by meejah** [comment] 2016-04-27 19:21
You can't use ``time.sleep`` in asynchronous code (neither asyncio nor Twisted).

**Comment by oberstet** [comment] 2016-04-27 19:34
@Tsunami2069 This is invalid, so don't open a new issue. `time.sleep` is blocking the reactor. Use `autobahn.twisted.util.sleep` or simiar for asyncio.

**Comment by oberstet** [comment] 2016-04-27 19:38
@DZabavchik `requests` will also block the reactor. What you do with threads "works" but is a hack/wrong. In fact, threads are almost always unnecessary and pain with no gain. Use https://github.com/twisted/treq instead.

> Threads are only needed when you absolutely have to use a blocking thing and there is no alternative OR when you are CPU bound and want to scale on multi-core - however, processes might then be better. So in conclusion: don't use threads.

**Comment by oberstet** [comment] 2016-04-27 19:39
Plus: PLEASE USE OUR MAILING LIST. This is a bug tracker.

**Comment by FirefighterBlu3** [comment] 2016-04-27 19:41
@Tsunami2069

I have a functioning system that I believe I resolved these issues with
by doing things [more ;)] correctly, the GH repo is at
https://github.com/Blue-Labs/ButterflyDNS and uses asyncio. (If others
have constructive criticism on my example, I'm happy to ack)

**Comment by oberstet** [comment] 2016-04-27 19:45
Yes, this looks much better. It uses `aiopg` for database access. This is one approach.

You can read up all your options for accessing PostgreSQL here http://crossbar.io/docs/Database-Programming-with-PostgreSQL/

**Comment by oberstet** [comment] 2016-04-27 19:46
And this code also (correctly) uses `yield from asyncio.sleep(1)` to sleep non-blocking ..

**Comment by oberstet** [comment] 2016-04-27 19:55
@FirefighterBlu3: OT, but what is ButterflyDNS doing;) I skimmed into the code, but not quite get the overall goal ..

**Comment by FirefighterBlu3** [comment] 2016-04-27 20:05
it's a web GUI front end for managing DLZ (dynamically loaded) DNS zones
in BIND that gets pushed to multiple nameservers immediately. uses
dynamic auth which will soon have per zone granularity for
none/read/readwrite access to zones. normally everything is zippy fast
but there is one segment of the in-zone tab that has a bunch of NS
digging for glue records and that can take many seconds to resolve as
well as a whois lookup to check expire timestamps at registrars, also laggy.

**Comment by oberstet** [comment] 2016-04-27 20:23
Huh, interesting! I'm not an DNS expert .. sounds specialized;) Nice job. Since it is open source, maybe announce it on the mailing lists? https://groups.google.com/forum/#!members/crossbario and https://groups.google.com/forum/#!members/autobahnws

**Comment by meejah** [comment] 2016-04-27 20:25
Also, I suggest @FirefighterBlu3 should copy his comment above into the README for ButterflyDNS :)

**Comment by FirefighterBlu3** [comment] 2016-04-27 20:30
i will do these things, thank you ;)
