### ISSUE TITLE
Conversion from JSON to YAML fails

### ISSUE THREAD

**Issue by herm** [crossbario/crossbar#701] opened 2016-04-06 20:46 UTC
Not even converting the template works:
```
xuser@bananapi:~$ mkdir crossbartest
xuser@bananapi:~$ cd crossbartest/
xuser@bananapi:~/crossbartest$ crossbar init
Automatically choosing optimal Twisted reactor
Running on Linux and optimal reactor (epoll) was installed.
Initializing application template 'default' in directory '/home/xuser/crossbartest'
Using template from '/usr/local/lib/python2.7/dist-packages/crossbar/templates/default'
Creating directory /home/xuser/crossbartest/.crossbar
Creating file /home/xuser/crossbartest/.crossbar/config.json
Application template initialized

To start your node, run 'crossbar start --cbdir /home/xuser/crossbartest/.crossbar'

xuser@bananapi:~/crossbartest$ crossbar convert
Automatically choosing optimal Twisted reactor
Running on Linux and optimal reactor (epoll) was installed.
Converting local configuration file /home/xuser/crossbartest/.crossbar/config.json
converting JSON formatted configuration /home/xuser/crossbartest/.crossbar/config.json to YAML format ...

Error: cannot represent an object: OrderedDict([(u'version', 2), (u'controller', OrderedDict()), (u'workers', [OrderedDict([(u'type', u'router'), (u'realms', [OrderedDict([(u'name', u'realm1'), (u'roles', [OrderedDict([(u'name', u'anonymous'), (u'permissions', [OrderedDict([(u'uri', u''), (u'match', u'prefix'), (u'allow', OrderedDict([(u'call', True), (u'register', True), (u'publish', True), (u'subscribe', True)])), (u'disclose', OrderedDict([(u'caller', False), (u'publisher', False)])), (u'cache', True)])])])])])]), (u'transports', [OrderedDict([(u'type', u'web'), (u'endpoint', OrderedDict([(u'type', u'tcp'), (u'port', 8080)])), (u'paths', OrderedDict([(u'/', OrderedDict([(u'type', u'static'), (u'directory', u'..')])), (u'ws', OrderedDict([(u'type', u'websocket')]))]))])])])])])
```

**Comment by oberstet** [comment] 2016-04-07 10:10
duplicate of #699

**Closed by oberstet** 2016-04-07 10:10 UTC

**Comment by herm** [comment] 2016-04-07 10:44
Actually this is not a duplicate. #699 is about upgrading from an old config version. This bug is about conversion between JSON and YAML.

**Comment by oberstet** [comment] 2016-04-07 16:10
@herm Conversion in both directions works for me (now .. using trunk) .. could you please check if it works for you too?

```console
(python279_1)oberstet@thinkpad-t430s:~/node4$ ls -la
insgesamt 8
drwxrwxr-x   2 oberstet oberstet 4096 Apr  7 18:08 .
drwxr-xr-x 114 oberstet oberstet 4096 Apr  7 17:54 ..
(python279_1)oberstet@thinkpad-t430s:~/node4$ crossbar init
Initializing application template 'default' in directory '/home/oberstet/node4'
Using template from '/home/oberstet/python279_1/lib/python2.7/site-packages/crossbar-0.13.1-py2.7.egg/crossbar/templates/default'
Creating directory /home/oberstet/node4/.crossbar
Creating file /home/oberstet/node4/.crossbar/config.json
Application template initialized

To start your node, run 'crossbar start --cbdir /home/oberstet/node4/.crossbar'

(python279_1)oberstet@thinkpad-t430s:~/node4$ crossbar convert
Converting local configuration file /home/oberstet/node4/.crossbar/config.json
converting JSON formatted configuration /home/oberstet/node4/.crossbar/config.json to YAML format ...
ok, YAML formatted configuration written to /home/oberstet/node4/.crossbar/config.yaml
(python279_1)oberstet@thinkpad-t430s:~/node4$ rm .crossbar/config.json 
(python279_1)oberstet@thinkpad-t430s:~/node4$ crossbar check
Checking local node configuration file: /home/oberstet/node4/.crossbar/config.yaml
Ok, node configuration looks good!
(python279_1)oberstet@thinkpad-t430s:~/node4$ crossbar convert
Converting local configuration file /home/oberstet/node4/.crossbar/config.yaml
converting YAML configuration /home/oberstet/node4/.crossbar/config.yaml to JSON ...
ok, JSON formatted configuration written to /home/oberstet/node4/.crossbar/config.json
(python279_1)oberstet@thinkpad-t430s:~/node4$ rm .crossbar/config.yaml 
(python279_1)oberstet@thinkpad-t430s:~/node4$ crossbar check
Checking local node configuration file: /home/oberstet/node4/.crossbar/config.json
Ok, node configuration looks good!
(python279_1)oberstet@thinkpad-t430s:~/node4$ 
```

**Comment by herm** [comment] 2016-04-07 17:20
I had to update autobahn and txaio to trunk as well, otherwise crossbar would not start. But now converting between both formats works.

**Comment by oberstet** [comment] 2016-04-07 17:25
@herm perfect. thanks!

> Yeah, the code base of Crossbar.io heavily relies on Autobahn(Python), which in turn relies on txaio. All 3 are co-developed by us, and the recent refactoring of logging (nearly finished) required parallel changes in all 3.
