### ISSUE TITLE
Dangling wamp sessions

### ISSUE THREAD

**Issue by rafzi** [crossbario/crossbar#499] opened 2015-11-01 16:39 UTC
In a certain case crossbar will keep WAMP sessions forever. This is while using the autoping feature.

- WAMP client does not send GOODBYE.
- WAMP client sends websocket shutdown: Frame with opcode = close. (status = 1000)
- The connection is lost. Crossbar will not receive a RST. This can happen on application crashes or problems on the physical connection.

Crossbar does not send any more autopings, which makes sense because the autopings are on websocket level and the socket is closed.

But the socket and WAMP session stay alive which is bad in a production environment. Especially if you implement some quotas based on number of sessions (session.on_join, session.on_leave).

**Comment by Paranaix** [comment] 2015-11-04 19:36
I can reproduce this

**Comment by meejah** [comment] 2015-11-05 20:05
Does either of you have some component code that can reliably repeat this? I tried creating one that does what @rafzi describes by connecting successfully, sending a ``.close()`` on the transport and immediately killing myself with ``SIGKILL`` which doesn't "work" (i.e. the session gets removed).

I was testing "is there a hanging session" by starting a (different) session and calling ``wamp.session.list`` to see if there was an extra entry. I also monitored ``on_join`` and ``on_leave`` which I do get via the above-described test...

**Comment by oberstet** [comment] 2015-11-05 20:53
@meejah did you try that over a loopback connection, over a LAN or over an Internet connection? also: there are timeout options which you can set on the WebSocket transport level. However, what @rafzi describes .. it might happen, because we lack timeout knobs at the WAMP session teardown level? Not sure if that even applies. Actually, @rafzi I'm not sure if I understand .. a minimal reproducing example would be helpful finding out what's going on ..

**Comment by meejah** [comment] 2015-11-05 21:06
I have only tried over loopback thus far; it might be more productive to try to make a unit-test that demonstrates it as it's easier to control timing of events etc that way.

**Comment by oberstet** [comment] 2015-11-05 21:10
The problem with creating a unit test could be, that the scenario only applies with a real remote network connection, because a process kill will clean up the attached sockets because both event happen in one running kernel. But with a remote network connection where bytes just appear to be very very slow .. or the whole connection gone is hard to tell locally. So the unit test would need to be distributed over a network.

**Comment by oberstet** [comment] 2015-11-05 21:13
If you connect your notebook both over Wifi and over Ethernet to some Wifi router with switch ports, that should be a reasonable network connection. In other words, the host running dual interfaces connected to one network should be enough for the unit test as well.

**Comment by meejah** [comment] 2015-11-05 21:25
I meant a "real" unit-test, with no actual network stuff happening (i.e. ``StringTransports`` or otherwise mocked/faked). It might be "hard" in this case, but in the end more reliable than trying to fake a cut network cable ;)

Still, it would be nice to see it happen "for real" at least once :)

**Comment by rafzi** [comment] 2015-11-05 23:37
The situation of a program ending without sending a TCP reset might be hard to reproduce. I was running a native C++ application on Windows and when it crashed the "just in time" debugging feature kicked in. I'm pretty sure that on Linux SIGKILL does not prevent the kernel from sending a TCP reset on remaining open connections of the process.

I'm sorry it would be pretty complex to reduce the program to a minimal repro and it wouldn't be very minimal. It might possibly not even work on Linux.

Can you try reproducing the problem by connecting to a remote router, pausing the program after the websocket close frame and then simply pulling the ethernet plug?
Alternatively try to crash python on Windows with a JIT debugger installed. Or simply leave it pause forever - it represents the same situation and that case can even be tested via localhost.

**Comment by oberstet** [comment] 2015-11-06 08:39
@rafzi As said, we have configurable timeouts. Please try these settings: http://crossbar.io/docs/WebSocket-Options/#production-settings

Closing, as we can't reproduce.

**Closed by oberstet** 2015-11-06 08:39 UTC
Labels: needs-investigation

**Comment by rafzi** [comment] 2015-11-06 18:04
@oberstet Those settings were active, but the problem occurs after the closing handshake. It is expected that the router closes the connection.

I took the time to investigate. Had no luck at all with a python component where I overrode `onCloseFrame` to do nothing. The server just closed the TCP connection after answering to the close frame.

Then I tried reproducing a minimal version of my C++ app. At first the result was the same. The server closed TCP after responding to ws close.

But when I enabled TLS, I had a repro. The only change between working an non-working is TLS enabled.

Wireshark log. Notice the missing TCP FIN or RST at the end.
![](https://lh3.googleusercontent.com/-7kwwAqWUouU/VjzoaKx2zPI/AAAAAAAAB3Y/_v0iY_BqSfI/s0/2015-11-06_18-50-28.png)

---

router config.json

```
{

    "controller": {

    },

    "workers": [

        {

            "type": "router",

            "options": {

                "pythonpath": ["../../../"]

            },

            "realms": [

                {

                    "id": "main",

                    "name": "main",

                    "roles": [

                        {

                            "name": "anonymous",

                            "permissions": [

                                {

                                    "uri": "*",

                                    "publish": true,

                                    "subscribe": true,

                                    "call": true,

                                    "register": true

                                }

                            ]

                        }

                    ]

                }

            ],

            "transports": [

                {

                    "type": "websocket",

                    "endpoint": {

                        "type": "tcp",

                        "port": 12323,
                        "tls": {
                            "key": "ws.key",
                            "certificate": "ws.crt",
                            "dhparam": "dhparam.pem"
                        }

                    },

                    "options": {

                        "enable_webstatus": false,

                        "enable_hixie76": false,

                        "max_frame_size": 1048576,

                        "max_message_size": 1048576,

                        "auto_fragment_size": 65536,

                        "fail_by_drop": true,

                        "open_handshake_timeout": 2500,

                        "close_handshake_timeout": 1000,

                        "auto_ping_interval": 10000,

                        "auto_ping_timeout": 5000,

                        "auto_ping_size": 4

                    },

                    "auth": {

                        "anonymous": {

                            "role": "anonymous"

                        }

                    }

                }

            ]

        }

    ]

}
```

component config.json

```
{

    "controller": {

    },

    "workers": [

        {

            "type": "container",

            "options": {

                "pythonpath": ["../.."]

            },

            "components": [

                {

                    "type": "class",

                    "classname": "dang.DangSession",

                    "realm": "main",

                    "transport": {

                        "type": "websocket",

                        "endpoint": {

                            "type": "tcp",

                            "host": "REMOTEIPADDR",

                            "port": 12323,
                            "tls": {
                            }

                        },

                        "url": "wss://REMOTEIPADDR:12323"

                    }

                }

            ]

        }

    ]

}
```

Test component:

```
from twisted.internet.defer import inlineCallbacks
from twisted.logger import Logger

from autobahn.twisted.util import sleep
from autobahn.twisted.wamp import ApplicationSession


class DangSession(ApplicationSession):

    log = Logger()

    @inlineCallbacks
    def onJoin(self, details):

        def onjoin(details):
            self.log.info("on_join")

        def onleave(details):
            self.log.info("on_leave")

        yield self.subscribe(onjoin, "wamp.session.on_join")
        yield self.subscribe(onleave, "wamp.session.on_leave")


```

C++ app (sorry for so many includes, it's from my general test app):

```
#undef UNICODE
#define NOMINMAX
#include "Poco/Net/StreamSocket.h"
#include "Poco/Net/SocketStream.h"
#include "Poco/Net/MulticastSocket.h"
#include "Poco/StreamCopier.h"
#include "Poco/Net/DatagramSocket.h"
#include "Poco/ByteOrder.h"
#include "Poco/Net/HTTPRequest.h"
#include "Poco/Net/HTTPResponse.h"
#include "Poco/Net/HTMLForm.h"
#include "Poco/Net/HTTPClientSession.h"
#include "Poco/InflatingStream.h"
#include "Poco/JSON/Parser.h"
#include "Poco/Base64Encoder.h"
#include "Poco/Net/ICMPSocket.h"
#include "Poco/Net/ICMPPacket.h"
#include "Poco/Net/RawSocket.h"
#include "Poco/JSON/JSON.h"
#include "Poco/TemporaryFile.h"
#include "Poco/Net/Context.h"
#include "Poco/Net/HTTPSClientSession.h"
#include "Poco/Net/WebSocket.h"
#include "Poco/RecursiveDirectoryIterator.h"
#include "Poco/DirectoryIteratorStrategy.h"
#include "Poco/TimedNotificationQueue.h"
#include "Poco/File.h"
#include "Poco/Path.h"
#include "Poco/Logger.h"
#include "Poco/FileChannel.h"
#include "Poco/NamedEvent.h"
#include "Poco/Event.h"
#include "Poco/Process.h"
#include "Poco/Util/WinRegistryKey.h"
#include "Timer.h"
#include <vector>
#include <stack>
#include <iostream>
#include <cstdio>
#include <tuple>
#include <map>
#include <set>
#include <cstdarg>
#include <cstdint>
#include <memory>
#include <functional>
#include <future>
#include <thread>
#include <Windows.h>
//#include <WinSock2.h>
#include <sstream>
#include <chrono>
#include <atomic>
#include <string>
#include <iostream>
#include <iomanip>
#include <d3dx9.h>
#include <TlHelp32.h>



#include <thread>
#include <memory>
#include <cstdio>



void sendJSON(Poco::Net::WebSocket& ws, const Poco::JSON::Array& json)
{
    std::stringstream ssout;
    json.stringify(ssout);
    auto sendSize = static_cast<size_t>(ssout.tellp());
    std::vector<char> buf(sendSize);
    ssout.read(buf.data(), sendSize);
    ws.sendFrame(buf.data(), sendSize);
}

int main(int argc, char *argv[])
{
    Poco::Net::SocketAddress addr(argv[1], 12323);

    Poco::Net::HTTPRequest request("GET", "/ws", Poco::Net::HTTPRequest::HTTP_1_1);
    request.add("Sec-WebSocket-Protocol", "wamp.2.json");

    //Poco::Net::HTTPClientSession session(addr);
    Poco::Net::Context ctx(Poco::Net::Context::CLIENT_USE, "", Poco::Net::Context::VERIFY_NONE, 9, true);
    Poco::Net::HTTPSClientSession session(addr.host().toString(), addr.port(), &ctx);

    Poco::Net::HTTPResponse response;
    Poco::Net::WebSocket ws(session, request, response);

    Poco::JSON::Array hello;
    hello.add((int)1);
    std::stringstream ss;
    hello.stringify(ss);
    hello.add("main");
    Poco::JSON::Object roles;
    roles.set("caller", Poco::JSON::Object());
    roles.set("callee", Poco::JSON::Object());
    roles.set("publisher", Poco::JSON::Object());
    roles.set("subscriber", Poco::JSON::Object());
    Poco::JSON::Object details;
    details.set("roles", roles);
    hello.add(details);
    sendJSON(ws, hello);

    char buf[4096];
    int flags;
    ws.receiveFrame(buf, sizeof(buf), flags);

    std::this_thread::sleep_for(std::chrono::seconds(3));

    printf("shutdown\n");
    ws.shutdown();

    int crash = *(int*)nullptr;

    //std::cin.ignore();
}
```

**Comment by meejah** [comment] 2015-11-06 18:12
@rafzi thanks for the detailed update!

**Comment by meejah** [comment] 2015-11-06 18:47
FWIW, re-running my simple localhost test with TLS still works properly ...

**Comment by rafzi** [comment] 2015-11-06 19:21
Here is a component that replicates the C++ one. It is tested via remote connection over the internet.

```python
from twisted.internet.defer import inlineCallbacks
from twisted.internet import reactor
from twisted.logger import Logger

from autobahn.twisted.util import sleep
from autobahn.twisted.wamp import ApplicationSession

import os
import signal


def onCloseFrameDummy(code, reasonRaw):
    print("oncloseframedummy")
    os.kill(os.getpid(), signal.SIGSTOP)


class DangSession(ApplicationSession):

    log = Logger()

    def onJoin(self, details):

        self._transport.onCloseFrame = onCloseFrameDummy

        def closeit():
            self._transport.sendCloseFrame(1000)

        reactor.callLater(1, closeit)

```

**Comment by rafzi** [comment] 2015-11-11 19:20
Is there a reason that this is still closed? I hope it won't be forgotten.

**Comment by meejah** [comment] 2015-11-18 16:53
@rafzl I think we can re-open if/when there is a way to repeat the bug.

I will try again over a non-LAN internet connection with the component above, but could not replicate it on a local net (even between two "real" machines).
