### ISSUE TITLE
Missing images in documentation

### ISSUE THREAD

**Issue by johngeorgewright** [crossbario/crossbar#905] opened 2016-10-16 17:15 UTC
All the images on this page are missing: http://crossbar.io/docs/Architecture/

**Comment by braingineer** [comment] 2016-10-22 17:37
also, 
http://crossbar.io/docs/Router-Transports/

**Comment by hawkowl** [comment] 2016-11-15 12:54
Duplicate of https://github.com/crossbario/crossbar/issues/876

**Closed by hawkowl** 2016-11-15 12:54 UTC
