### ISSUE TITLE
HTTP/WAMP bridge

### ISSUE THREAD

**Issue by sametmax** [crossbario/crossbar#188] opened 2014-12-29 10:45 UTC
I wrote an article (http://sametmax.com/bridge-httpwamp/) but in french, so I'm going to translate the essence of it here:  

They are 4 big show stoppers for WAMP adoption:

- incomprehension. People don't know what it's for, what they can do with it. They are scared. It's only logical, and it's the same with anything new. Investing in a new stuff has a cost, espacially if it's young.
- documentation. I'm the solution.
- API. It goes with the former points. You need something higher level. The flask-like API is a good start, you need to carry on in that direction.
- integration with previous stack, such as Django. No one want to trash all the previous work.

All libs implying a new way of working meet theses issues. It was the same with ORMs, Django, Rails, Symfony...

But since we know about it, we can do something.

We already took first steps to resolve the first 3 issues, let's see what we can do about the last one.

There are a lot of stuff to do about integration : authentication, blocking actions, communications...

We can't solve it all with one blow, but there is a solution that is generic enough : create an HTTP/WAMP bridge.

In brief : make a WAMP client that is also an HTTP client with a REST API

Concept
========

You can make HTTP resquests on the bridge, with a webtoken for authentication, to make register/subscribe/call/publish and specify a callback URL. The bridge relays that to the WAMP router. Once an event arrives on the bridge concerning a callback URL, it makes a request on it containing the WAMP informations.

API:

POST /register/

```

{
    // authentication token
    token: "fdjsklfqsdjm",
    // We register a callback URL for each "function" you register for RPC
    // When the bridge receives the RPC call via WAMP, it will make a 
    // POST resquest to the proper URL. The legacy HTTP app then get
    // the data via POST and shall return JSON to the bridge, which will relay
    // it in WAMP
    endpoints: {
        "func_name_1":  "http://localhost:8080/wamp/rpc/func_name_1/",
        "func_name_2":  "http://localhost:8080/wamp/rpc/func_name_2/"
    }
}
```

POST /subscribe/

```
{
    token: "fdjsklfqsdjm",
    // We register callback URLs for each subscription to a topic.
    // When the bridge receives a published message, it will make a POST request
    // to the proper URL. The legacy HTTP app receives data via POST.
    endpoints: {
        "func_name_1":  "http://localhost:8080/wamp/pub/func_name_1/",
        "func_name_2":  "http://localhost:8080/wamp/pub/func_name_2/"
    }
}
```

POST /call/func_name/

```
{
    token: "fdjsklfqsdjm",
    // The bridge will make the RPC call, get the return value, then
    // post it back to this URL via POST (or a 500 error if needed)
    callback: "http://localhost:8080/wamp/callback/func_name",
    // Params to pass to RPC
    params: ['param1', 'param2']
}
```

POST /publish/nom_sujet/

```
{
    token: "fdjsklfqsdjm",
    // Bridge will make the WAMP publication with these params
    params: ['param1', 'param2']
}
```

You can even add more tools : reload the config files containing the API keys, unregistering, unsusbribing...

Of course, since we got a middle man, it's not very performant. But sufficient to allow a communication with legacy HTTP apps and WAMP and start using it.

Stronger integration
======================

This would allow a generic integration, so anybody can integrate a legacy app with a bunch of HTTP requests. However, having a plugin for the most important frameworks would help a lot of people. 

So, step 2 is to make plug and play wrappers. 

Django example:

settings.py

```
WAMP_BRIDGE_URL = "http://localhost:8181/"
```

urls.py

```
from wamp_bridge.adapters.django import dispatcher
 
urlpatterns += ('',
    url('/wamp/, dispatcher),
    ...
)
```

views.py

```
from wamp_bridge.adapters.django import publish, call, rpc, sub
 
@rpc()
def func_name_1(val1, val2):
    # do stuff
 
@sub()
def nom_topic_1(val1, val2):
    # do stuff
 
def classic_view(request):
    publish('sujet', ['arg1'])
    resultat = call('function', ['arg1'])
```

This does not solve some issues such as : "how do I keep my Django auth process ?", but it's already great. It would make stop people wondering "what can I do ?" and and change it to "let's test that !"

Implementation
==============

We can create the bride in many languages, but if we want to integrate it with crossbar, Python is the most interesting.

We need Python 2 and 3 implementation, so one with Twisted (using twisted web for the server and treq for the client) and one with asycio (using aiohttp client and server).

But Python 2 is the priority, since twisted is being ported to Python 3, we may benefit from it.

Although, joining the effort to port twisted to Python 3 could help a lot.

**Comment by oberstet** [comment] 2015-01-10 17:03
In essence, this is a duplicate of #23, but I leave it open because of the amount of comments/text here ..

**Comment by oberstet** [comment] 2015-04-07 19:35
implemented now

**Closed by oberstet** 2015-04-07 19:35 UTC
Labels: core, enhancement
