### ISSUE TITLE
Buildroot support

### ISSUE THREAD

**Issue by yegorich** [crossbario/crossbar#1126] opened 2017-07-06 14:23 UTC
Buildroot support for crossbar is still WIP. There are basically two issues:

1. crossbar/worker/test/examples/syntaxerror.py: by default BR compiles all py files to pyc and also checks if the compilation process was successful. This file cannot be compiled successfully as it purposefully contains a syntax error. This will be fixed by a local [patch](https://git.busybox.net/buildroot/tree/package/python-crossbar/0001-Avoid-intentional-syntax-error.patch). 

2. BR provides either Python 2 environment or Python 3 hence such packages as ipaddress, enum34 and shutilswhich are missing in Python 3 environment. This issue is addressed in https://github.com/crossbario/crossbar/pull/1125

Other than that I could successfully execute following commands using Python 3 and compiled Python files only (*.pyc):

```
crossbar init --template default --appdir hello
crossbar start --cbdir /root/hello/.crossbar
```

**Comment by Evidlo** [comment] 2017-09-30 02:20
Have you tested this in Python 2?  I got the following errors, which according to [here](https://stackoverflow.com/questions/20399331/error-importing-hashlib-with-python-2-7-but-not-with-2-6) is indicative of missing OpenSSL libs.

`ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "usr/lib/python2.7/hashlib.py", line 147, in <module>
  File "usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "usr/lib/python2.7/hashlib.py", line 147, in <module>
  File "usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "usr/lib/python2.7/hashlib.py", line 147, in <module>
  File "usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "usr/lib/python2.7/hashlib.py", line 147, in <module>
  File "usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "usr/lib/python2.7/hashlib.py", line 147, in <module>
  File "usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "usr/lib/python2.7/hashlib.py", line 147, in <module>
  File "usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
ValueError: unsupported hash type sha512`

**Comment by yegorich** [comment] 2017-09-30 06:34
What Buildroot version are you using? I've fixed this issue in the master branch, i.e. python-cryptography now also selects hashlib when building Python 2.

**Comment by Evidlo** [comment] 2017-09-30 06:37
I was using rpi-buildroot.  I've since switched to build root proper and I can confirm it works.

**Comment by oberstet** [comment] 2018-05-09 19:55
As to the OPs two issues:

1. the `syntaxerror.py`: as I understand this is fixed by a local patch. in this case, I'd rather leave the file in place. I'd be willing to look for a different solution on our side, even remove it, should the patch be a problem
2. rgd the three mentioned package: those are removed on master, pls see my comments here https://github.com/crossbario/crossbar/issues/1235#issuecomment-387854941

So I am closing this one for now, as I assume "it works on buildroot" - feel free to reopen if there are open issues left!

**Closed by oberstet** 2018-05-09 19:55 UTC
Labels: core, enhancement
