### ISSUE TITLE
Crossbar Doesn't Send Subscribers Match Request To Authorizor

### ISSUE THREAD

**Issue by motosota** [crossbario/crossbar#304] opened 2015-04-14 05:32 UTC
With dynamic authorization configured, the authorization service doesn't seem to receive the requesting subscriber's match request (prefix / wildcard).

It seems it would be useful for the authrorizor to allow / deny based on this together witht the uri.

Checked on the issues list and this was the closest https://github.com/crossbario/crossbar/issues/280 but is for static authorization

**Comment by oberstet** [comment] 2016-04-08 13:19
Duplicate of https://github.com/crossbario/crossbar/issues/430

**Closed by oberstet** 2016-04-08 13:19 UTC
Labels: core, enhancement
