### ISSUE TITLE
wamp.session.on_leave sent for own session

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#244] opened 2015-02-13 14:48 UTC
If a session subscribed `wamp.session.on_leave` it receives an event for its own leave. As that event is sent after the session left, this results in ill behaviour. Here is my log output:

```
2015-02-13 15:40:18+0100 [Container    4126] global name 'error' is not defined
2015-02-13 15:40:18+0100 [Container    4126] Registration of one or more services failed, terminating...
2015-02-13 15:40:18+0100 [Container    4126] TX WAMP GOODBYE Message (message = None, reason = wamp.close.normal)
2015-02-13 15:40:18+0100 [Container    4126] RX WAMP GOODBYE Message (message = None, reason = wamp.goodbye.normal)
2015-02-13 15:40:18+0100 [Container    4126] RX WAMP EVENT Message (subscription = 880141810, publication = 464181522, args = [{u'realm': u'main', u'authprovider': u'dynamic', u'authid': u'$Backend', u'authrole': u'backend', u'authmethod': u'wampcra', u'session': 1408713439, u'transport': {u'peer': u'tcp4:127.0.0.1:48447', u'type': u'websocket', u'protocol': u'wamp.2.json.batched', u'http_headers_received': {u'upgrade': u'WebSocket', u'sec-websocket-version': u'13', u'sec-websocket-protocol': u'wamp.2.json.batched,wamp.2.json', u'host': u'localhost:9090', u'sec-websocket-key': u'a3PZyO/Aqr7IOC/KhPPAjg==', u'user-agent': u'AutobahnPython/0.9.4-2', u'connection': u'Upgrade', u'pragma': u'no-cache', u'cache-control': u'no-cache'}, u'http_headers_sent': {}}}], kwargs = None, publisher = None)
2015-02-13 15:40:18+0100 [Container    4126] Traceback (most recent call last):
2015-02-13 15:40:18+0100 [Container    4126] File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/websocket.py", line 91, in onMessage
2015-02-13 15:40:18+0100 [Container    4126] self._session.onMessage(msg)
2015-02-13 15:40:18+0100 [Container    4126] File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/protocol.py", line 429, in onMessage
2015-02-13 15:40:18+0100 [Container    4126] raise ProtocolError("Received {0} message, and session is not yet established".format(msg.__class__))
2015-02-13 15:40:18+0100 [Container    4126] ProtocolError: Received autobahn.wamp.message.Event message, and session is not yet established
2015-02-13 15:40:18+0100 [Container    4126] Failing WAMP-over-WebSocket transport: code = 1002, reason = 'WAMP Protocol Error (Received autobahn.wamp.message.Event message, and session is not yet established)'
2015-02-13 15:40:18+0100 [Container    4126] WAMP-over-WebSocket transport lost: wasClean = False, code = 1006, reason = 'connection was closed uncleanly (I failed the WebSocket connection by dropping the TCP connection)'
```

**Comment by oberstet** [comment] 2015-03-09 20:15
The monitor https://github.com/crossbario/crossbarexamples/tree/master/metaapi subscribes to session metaevents and can be closed itself via button. I can't reproduce above with the current code. The code underwent a large change recently though.

**Closed by oberstet** 2015-03-09 20:15 UTC
Labels: bug, core
