### ISSUE TITLE
Container startup behavior

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#288] opened 2015-04-02 14:20 UTC
My bad that I haven't opened this earlier as this is an issue with crossbar for quite a while. There is currently no clean way to terminate a component or a node. While `ApplicationSession.disconnect()` can be called, this only disconnects the WAMP session but crossbar does not take notice of this and assumes that the session is up and running.

Usecases are especially error handling: E.g errors during startup (configuration, availability etc.) and errors during the registration process (can't register methods, can't call methods or a method of another peer which is called at the beginning is not available).

**Comment by meejah** [comment] 2015-04-06 16:17
Can you outline your use-case more? I'm not sure I understand correctly. 

You want a way to kill off a guest worker from within crossbar?

If the worker is still running, but just disconnected, crossbar will see that the process is still alive. Guest workers don't *have* to be WAMP session participants, from what I understand.

Does adding code to kill off your process in ``onDisconnect`` or similar work for your use-case? That is, make sure that your worker dies completely if the WAMP session disconnects?

**Comment by Paranaix** [comment] 2015-04-09 08:18
Sorry for the late reply.

Im not talking about guest workers here but about cotainer workers.
I just copied one snippet from our codebase that outlines the usecase:

``` python
    @inlineCallbacks
    def onJoin(self, details):
        try:
            yield self.register(self)

            options = RegisterOptions(details_arg = "_wampDetails")
            yield self.RegisterServices(self.authService,
                                        self.authAPI,
                                        self.botService,
                                        self.botAPI,
                                        self.serverService,

                                        registerOptions = options)

        except Exception as e:
            print e
            print "Registration of one or more services failed, terminating..."

            self.leave()
```

**Comment by Paranaix** [comment] 2015-04-09 19:17
This might relate to https://github.com/crossbario/crossbar/issues/276

**Comment by oberstet** [comment] 2015-04-09 21:19
A container worker can host multiple components. Each of these can be shut down by leave and disconnect.

The container worker itself can't be stopped by app components running within, but only by Crossbar.io node controller (that spawned the container worker). This is by design, since the fact that a component is running inside a container worker should be hidden from the component. It's a deployment thing that should be of no concern to the app.

_Dynamically_ stopping (or starting) workers will be possible via the Crossbar.io management API. For now, workers are started as configured in the (static) node configuration only, and stop when Crossbar.io stops.

**Comment by oberstet** [comment] 2015-04-09 21:20
Yah, this is *not* related to #276

**Comment by meejah** [comment] 2015-04-09 21:56
Perhaps if a component throws an exception during construction or ``onJoin``, it should be fatal (and crossbar will exit). This would mirror what happens if, e.g., you can't start a transport due to a port conflict.

**Comment by meejah** [comment] 2015-04-09 22:02
(This could relate to #276 in that I think exiting is probably the right behavior there, and so if it's the desired behavior for onJoin errors, too, then the solution is probably similar).

**Comment by oberstet** [comment] 2015-04-09 22:12
When a container starts, it starts with no components hosted at all. Then, the node controller will start components as configured in the static node config one by one. This is done via the API

* https://github.com/crossbario/crossbar/blob/master/crossbar/worker/container.py#L122
* https://github.com/crossbario/crossbar/blob/master/crossbar/worker/router.py#L258

When the node controller runs through a static node config, and encounters an error (eg a component can't be started or a transport can't be started), this is fatal. The node won't start at all.

However, above API is intended to be used in 2 ways:

1. being invoked by running through static config (https://github.com/crossbario/crossbar/blob/master/crossbar/controller/node.py#L107)
2. being invoked from remote management app

The former is implemented today, the latter is not yet here. When we have it, failure to start a component or transport isn't fatal for the node.

**Comment by meejah** [comment] 2015-04-09 22:25
Actually, it's not fatal if a component can't be started; e.g. if you have a component that just does ``raise RuntimeError("error")`` in its __init__ then the success() handler on container.py:283 runs fine because the factory-method isn't called until ``onOpen`` and so ``start_container_component`` returns successfully (because we connected), but then the process exits very shortly thereafter.

What if we add ``on_component_exit`` to the container worker, and the node-controller can deal with that event as it likes. I'd say that if any component exits "really soon" after start-up it should probably be fatal (at least in the static config case).

This could easily be configurable behavior if required, too...

**Comment by meejah** [comment] 2015-04-09 22:54
#263 might be relevant, too? It's sort of a similar feature (if worker shuts down, shutdown crossbar).

**Comment by oberstet** [comment] 2015-04-09 23:09
> Actually, it's not fatal if a component can't be started

Oh, I see. That's not what I wanted;) Bug bug.

Here is what I think would make sense (need to think hard though):

1. transport for component can't be established => `start_container_component` should fail (as it already does)
2. component can't be instantiated => `start_container_component` should already fail (this isn't the case today, but it should)
3. when transport was established and component instantiated (but before session joins a realm), `start_container_component` should return successfully and `on_component_start` (https://github.com/crossbario/crossbar/blob/master/crossbar/worker/container.py#L287) should be published.
4. when the transport disconnects, `on_component_stop` should be published.

A component should still have the ability to join/leave multiple times over the same underlying transport. Which is why `start_container_component` should already return (and `on_component_start` be fired) before a session is established, and `on_component_stop` only fire when the transport ends.

> Lately, there have been a whole bunch of start/restart/stop etc related issues/questions. In general, we need to address those in a way that works with both of above "modes": running from static config and running when connected to uplink remote management app.

**Comment by oberstet** [comment] 2015-08-23 13:43
@meejah can we close this?

**Comment by oberstet** [comment] 2015-08-28 12:53
implemented now. in particular, please see the example here https://github.com/crossbario/crossbarexamples/tree/master/containers/failures#the-component-exits-failure-5

**Closed by oberstet** 2015-08-28 12:53 UTC
Labels: bug, core

**Comment by oberstet** [comment] 2015-08-28 12:55
@Paranaix please let us know if the test case covers your original itch. if not, please submit a new issue. thx!
