### ISSUE TITLE
No pictures on crossbar.io

### ISSUE THREAD

**Issue by schoonc** [crossbario/crossbar#876] opened 2016-09-19 11:31 UTC
Example at the bottom of the page http://crossbar.io/docs/Router-Transports/
How to fix? Copy missing pictures to crossbar/docs/static from crossbardocs/static?
I could help.

**Comment by normanjaeckel** [comment] 2016-10-10 20:35
I got this:
```
404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: static/img/docs/gen/crossbar_transports_2.png
    RequestId: 50483051A7A00D84
    HostId: 6dhySuLHYjkLcFI4jGhqBpif1nIlFyxaJDaYoGiyDfynS6Z6I/8goNshBYRXaJ6KwfgVv+9Irqg=
```

**Comment by oberstet** [comment] 2016-10-11 22:02
Yeah, broken=( This is fallout of the integration of docs into this repo (which formerly lived elsewhere).

**Comment by oberstet** [comment] 2016-10-11 22:05
Thing is, we don't want to put pictures in this repo, but the plain docs .. these pictures are more "high level" and illustrative, and hence we should move them to our (private) repo for the http://crossbar.io web site - and fix the above .md to no longer reference these.

**Comment by hawkowl** [comment] 2016-11-15 12:54
https://github.com/crossbario/crossbar/issues/905 is a duplicate of this

**Closed** 2016-11-15 13:30 UTC
Labels: bug, docs

**Comment by normanjaeckel** [comment] 2016-11-15 13:32
Hm. Now both issues are closed. I think this is not what you wanted to do.

**Comment by oberstet** [comment] 2016-11-15 13:36
The picture links are already removed from the repo docs - we just need to redeploy the docs to the live Web site.
