### ISSUE TITLE
Make compiled extensions optional (again)

### ISSUE THREAD

**Issue by sametmax** [crossbario/crossbar#626] opened 2016-01-31 15:57 UTC
Hi ! Very nice release. I'm writing an article on it today to share the love.

The new release of crossbar make a heavy use of compiled C extensions (cryptography, pyNaCL, etc), which mean it requires to install an entire compilation stack with tooling, headers et the like. It also mean it will take a lot of time to install on small machines such as the Raspberry Pi.

This makes the newcomer experience harder, and is not necessary. You don't need cryptography to be activated to start playing with it or write a small internal project. You don't need lmdb to be compiled if you don't plan to use the history feature with it.

The Twisted team is trying to move C extensions from requirements to extras for their project, it would be great to have that in crossbar too.

Wheels are still not supported on Linux, but even when it will be (it's ongoin), I think it's a good habit to have a pure Python strong base, and add accelerators and features on it.

**Comment by oberstet** [comment] 2016-01-31 16:15
Thanks for the nice words! Looking forward to a new article;)

Regarding your request:

The Twisted team is moving towards _wheels_ and _cffi_. The problem is less binary extensions per-se, but non-wheels and cpyext. All the extensions used by CB are available as wheels.

lmdb and cryptography: soon _core_ features will not work at all without these. And no: I am not going to reinvent "wheels" here;) Pun.

For Linux (and FreeBSD), we provide a complete packaged binary distribution of CB. For Pi, we'll have a complete system image soon.

So the best new comer experience is simply this:

```console
sudo apt-get install crossbar
``` 

Done. You get _everything_. Including bundled, decent PyPy and OpenSSL.

I am sorry to say: but it's unlikely we go back to this insane matrix of required x optional whatever combinations.

**Comment by oberstet** [comment] 2016-01-31 16:20
Here are the install instructions for binary packages:

* http://crossbar.io/docs/Installation-on-Ubuntu/
* http://crossbar.io/docs/Installation-on-CentOS/
* http://crossbar.io/docs/Installation-on-FreeBSD/

**Note: we need to release 0.12 binary packages still (not yet updated). And we need _full_ automation, so whenever there is a release on PyPI, it's released immediately as binary packages too.**

@hawkowl : ^ =)

**Comment by oberstet** [comment] 2016-01-31 16:28
Ah, one more note in this context: Crossbar.io will also move to _pinning exact versions_ of all dependencies.

This is another lesson learned. This whole thing is complex enough that it's simply a road to insanity when we don't know for sure what combination is actually run. It's also basically impossible to support commercially.

This will then mean: either you should use a virtualenv _dedicated_ to CB (and CB only), or use a binary package (which installs fully self-contained, on *nix under `/opt/crossbar`).

**Comment by sametmax** [comment] 2016-01-31 17:33
It means that to setup crossbar, an end user will need to choose between several installation methods and identify the one that is the most useful for him/her, but also learn each dawback.

I can see many people trying to do pip install crossbar without reading the doc, and then chasing dependencies when it fails.

But even when they do read the doc, it means people choosing apt-get will have an outdated version.

It also mean that any non supported platform will get a painful installation. You want to run it in a debian/centos Destop/Server Linux flavor ? You want to run it non official image for raspi ? BSD ? Running on an alternative Python implementation ? Porting crossbar to run on IOS or Android ? Any stuff we having though about yet ? It's way harder.

One of the big selling point of Python is almost free portability. By requiring C extension, it limits portability to selected platforms. Of course, I'm not advocating you should __support__ any of these platforms. But making it easy for people to hack around and try new stuff is very important. For that, it means not placing an artificial restriction on it. 

Then you got another big problem : embedding crossbar. 

I know you always want to make sure crossbar is a standalone product. But the thing is, embedding it has a great value. 

E.G: this week I have been asked to provide some software for a company building information systems for ports. They have censors everywhere : tide, wind, temp, light, AIS transponders, etc. and needed to aggregate them. Crossbar would be GREAT for that, except they want to ship the code inside their own software (which embed Python 2.7). They install everything offline, from external hard drive and DVD, and their system has no internet connection by design.

It would be much, much easier for me to be able to provide a zip with the crossbar code and mine, do from crossbar import Router; Router(some, params) and be happy. 

But right now I can't. I tried to hook on their installer so it also installs the router, then add it as a daemon on startup but failed. And now with these external dependencies it will be even harder because I'm guessing the internal imports assume the modules are available.

Bottom line: I will end up writting my own TCP server to concentrate these streams. It's silly. I got one of the best software of the decade, and I can't use it.

The world is not made of clean working environments. We need hackability. 

I also means you can't build a framework that makes the use of crossbar transparent. 

E.G: If I create a generic concentrator / translator for format such as NMEA (https://en.wikipedia.org/wiki/NMEA_0183), I can make a framework for the next teams which will be working on similar problems. But I can't embed crossbar in it. People must setup crossbar separately, I can't automate that easily for them. So it makes trying out the framework harder. 

Then of course you got my missions in Africa (not kidding). You want to install something, you don't always have internet at your disposal. You can't know which OS you are going to land on. With Python you don't care. Unzip. Run. With external C dependencies I can't do that anymore.

Than you got the missions in Asia (still not kidding). Here you got Internet, but many things are filtered of blocked, completely out of the blue for some hours or days, then work again. Sometime pip stops working. Or apt. Or ssh. Or anything really. Then again, with python you don't care. You unzip. Your run. 

In all theses cases, Python allow me to just keep on working. Event on machines I'm not prepared to work on. They just need Python. I'll figure out a better way for deployment, but right now, I just want to work please. And it works.

BTW: about pinning dependencies, you can specify a range. It's more work, but it's more flexible.

The way I see it, crossbar is trying to hide away more and more the fact it's written in Python instead of embracing it. I think it's great to make it more accessible to non Python programmers and make it friendly to sys admins and big infrastructures, but denying the community the capacity to use it as the great Python too it is, it downgrades our ability to enjoy it.

Again, frameworks like Django activate sqlite by default in their project templates. No MySQL. Not PostGres. Because it works out of the box.

With the current path crossbar is running to, it will become a product like Postgres or MySQL. A big black box. While there is a huge value to be able to manage it (install, deploy, etc) like Postgres or MySQL, there is no need to remove the ability to use it as a Python tool to do so. It is a very nice feature.

**Comment by oberstet** [comment] 2016-01-31 21:39
Thanks for the article! Awesome;)

Let me try to explain a little about the reasoning behind some design decisions that might appear arbitrary and limiting, but are indeed derived of some principles we try to stick to.

One of the cornerstones of WAMP is: decoupling. And that is meant in two dimensions: application components with relation to each other as well as application code and router code. Now, this might seem limiting, but in fact there is a implicit promise as well: if you follow the decoupling approach, then things will be easier! Complex, multi-component applications, with components distributed not only in processes on one machine, but on a local area, and even wide-area spanning network. Components can even reside behind NATed networks, with no open ports on the device hosting the component at all.

Further, components can talk any combination of WAMP with WebSocket, RawSocket and Long-Poll framing, as well as any of JSON, MessagePack and CBOR serialization, as well as any of TCP, TLS, Pipes and Unix domain sockets as stream transports.

This means: 3 x 3 x 4 = 36 transport types.

Further, you can implement your app components in any of a dozen WAMP supporting client libraries and languages.

Then you can extend Crossbar.io by implementing components which you configure to work as dynamic authenticators and authorizers.

Hold on, the list goes on;)

Then you have the REST bridge integration point. You can talk plain HTTP to Crossbar.io and use any of the 4 WAMP roles from a synchronous, blocking old school HTTP client to issue publishes or calls, or have your HTTP endpoint being called by Crossbar.io in response to a WAMP event or invocation.

When the PostgreSQL adapter is released, you'll have a direct-to-database integration point as well. Again, for all 4 WAMP roles.

Alright. I stop here. You see my point? There _are_ a whole multitude of integration points available, and they are all designed with one principle in mind: decoupling.

On the other hand: Crossbar.io really has support for Python even beyond that. When using the _same_ Python as the Crossbar.io one to implement a component, you can have Crossbar.io _host_ than in *container workers* and *router workers* as well. You cannot do that with component written in other languages. If you run Crossbar.io under Python 2, your component must be written supporting that. If you run Crossbar.io under Python 3, your component must run there. And you also cannot write Python 2/3 components using asyncio. Only Twisted. The reason is simple: Crossbar.io router and container workers run their own event loop, and that loop is a Twisted one.

So effectively, what you have posted on https://github.com/crossbario/crossbar/issues/627 (which is a bug, I guess :( would only run as a guest worker hosted by Crossbar.io.

You also should not import Crossbar.io Python classes from the `crossbar` package mainly for  these reasons:

* there is no public, supported Python level API in Crossbar.io
* _technically_, one can import Crossbar.io Python classes of course. the only thing is: the code importing Crossbar.io classes is effectively extending Crossbar.io, and hence needs to be licensed in a way compatible with the AGPL v3.0 (which is the license of Crossbar.io)
* decoupling

---

So in a way, take above as input for the discussion. I guess it would be cool to hear the thoughts of others as well=)

**Comment by oberstet** [comment] 2016-01-31 21:45
@sametmax I also feel, your original issue was much more focused, namely on a packaging question. Like in "Should Crossbar.io support strict Python code only, no native extensions installations"?

**Comment by sametmax** [comment] 2016-02-01 09:56
Indeed, I went a bit overboard. But C extensions are part of the deal. Now again, given you guys are doing a enormous work, asking you to do even more or to consider another policy is always a bit unfair. I'm just expressing my position and the way I wish to be able to use crossbar. The lack of external API is another issue (which maybe I should open a ticket on) but is a symptom of the current policy.

I also get a little touchy these days about making setup as bare as possible because of the ton of news build/deployment/setup tools we get to use these days as web dev. Simplicity for me is a feature, and pure Python is simplicity.

But thanks for taking the time to answer, and as usual, with great details. It's very nice to have somebody caring about the feedback.

**Comment by oberstet** [comment] 2016-02-01 10:45
> The lack of external API is another issue (which maybe I should open a ticket on) but is a symptom of the current policy.

That's not true. Crossbar.io **does** have an external API, it's just not Python-level, but WAMP-level.

Don't waste your time on such a ticket: it has zero chances;) There won't be a Python-level API.

**Comment by oberstet** [comment] 2016-02-10 09:44
Regarding the original question: no, sorry, we won't make things optional again.

Yes, getting Crossbar.io onto something like a Linux/MIPS device that lacks a on-device buildchain will require a full cross-build chain. Getting CB onto something like the Pi is trivial though. Getting CB onto a device without network: just ship a perbuilt tarball.

---

Regarding the many valuable arguments and discussion above: I have created https://github.com/crossbario/crossbardocs/issues/57 and linked to here.

I hopefully will find time to work on the doc issue, and then I will try to recap/cover our discussion above.

**Closed by oberstet** 2016-02-10 09:44 UTC
Labels: needs-discussion
