### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by basz** [crossbario/crossbar#270] opened 2015-03-17 13:34 UTC
Crossbar is using ~1Gb of memory after a day or two of doing (almost) nothing... That can't be right...

I run one node with supervisor, that exposes a pusher gateway (to which I push a message every few second) so I'm thinking these messages are being kept in memory.

What can I do to check this out?

Development setup. 

```
root@s2:~# cd crossbar-pypy-venv/
root@s2:~/crossbar-pypy-venv# . bin/activate
(crossbar-pypy-venv)root@s2:~/crossbar-pypy-venv crossbar version
Crossbar.io                  : 0.10.2

  Autobahn|Python            : 0.10.1
    WebSocket UTF8 Validator : autobahn
    WebSocket XOR Masker     : autobahn
    WAMP JSON Codec          : stdlib
    WAMP MsgPack Codec       : msgpack-python-0.4.5
  Twisted                    : 15.0.0-EPollReactor
  Python                     : 2.7.8-PyPy

OS                           : Linux-3.18.5-x86_64-linode52-x86_64-with-Ubuntu-14.04-trusty
Machine                      : x86_64
```
Running with supervisor
```
[program:crossbar-server]
command=/root/crossbar-pypy-venv/bin/crossbar start --cbdir /root/mynode/.crossbar
process_name=Crossbar
directory=/root/crossbar-pypy-venv
redirect_stderr=true
autostart=true
autorestart=true
user=root
numprocs=1
stdout_logfile=/root/mynode/logs/info.log
stdout_logfile_maxbytes=1MB
stderr_logfile=/root/mynode/logs/error.log
stderr_logfile_maxbytes=1MB
```

```
cat /root/mynode/.crossbar/config.json
```
see https://gist.github.com/basz/f1575a17b38731054e92

**Comment by estan** [comment] 2015-03-25 09:50
If this is the case I think it should be considered a high priority bug. It's a bit worrying since we're considering using Crossbar in an embedded environment, where the machine will be in service for three years in a remote locations, so memory leaks/accumulation would be a serious showstopper.

**Comment by oberstet** [comment] 2015-03-30 13:55
FWIW, we are running Crossbar.io on a public instance (demo.crossbar.io) with no restarts in weeks/months. But this isn't stressing the HTTP gateway ...

**Comment by basz** [comment] 2015-03-31 08:45
As a follow up, I noticed the following:

It really is the 'pusher' (now called 'publisher' - took a while to figure that one out) as the only thing pushing to it is my laptop. When the laptop is sleeping memory usage does not increase...

https://www.dropbox.com/s/6ga2z438c3j1w0x/Screenshot%202015-03-31%2010.38.56.png?dl=0

(I've now update to crossbar 0.10.3)

**Comment by basz** [comment] 2015-03-31 11:00
This behavior exists for both the TLS and the non TLS publisher endpoint

**Comment by oberstet** [comment] 2015-03-31 11:59
@hawkowl Could you have a look at this? Any clue what might be causing memory leakage?

**Comment by hawkowl** [comment] 2015-03-31 12:18
My first hunch is that the GC isn't cleaning out completed requests. I'll investigate :)

**Comment by oberstet** [comment] 2015-03-31 12:30
@basz @hawkowl If it is GC related, might be worth comparing CPython vs PyPy.

**Comment by hawkowl** [comment] 2015-04-01 05:13
Hmm. So far, I'm getting stable at ~103MB after sending 400K signed requests on PyPy 2.5.1, 105MB after 600K signed requests on PyPy 2.4.0, and 55MB after sending 150K signed requests on CPython 2.7.9. Over TLS (using the supplied config), PyPy 2.4.0 ends up at about ~120MB after 400K signed requests.

This is on OS X, though. I'll grab something with EPoll and try and reproduce it there.

**Comment by hawkowl** [comment] 2015-04-01 06:12
Hmm, on an Ubuntu 14.04 VM with the official Crossbar Debian package (PyPy 2.5, Crossbar 0.10.2), I'm stable at ~140MB after sending a million signed requests through it. So, I don't think it's the pusher portion, and it's not an EPoll issue.

@basz What is receiving the messages? Maybe something to do with that is causing the issue...

**Comment by oberstet** [comment] 2015-04-01 06:34
> Over TLS (using the supplied config), PyPy 2.4.0 ends up at about ~120MB after 400K signed requests.

Rgd the publisher (REST bridge) side of things, your test has all I can think of which could go wild:

* epoll
* PyPy (vs CPy)
* TLS
* signed requests

@basz Is the HTTP client that issues the requests to the publisher (REST bridge) properly closing HTTP connections? I mean, if it opens HTTP 1.1 keep-alive connections, but then doesn't reuse them for further requests, and doesn't close them either, that would be a problem. Can you check the number of open file descriptors on the process running the REST bridge (the Crossbar.io router worker) - `lsof -a -p 28290` on Linux. How many normal WAMP clients are connected to the router (try only a small fixed number and check if memory still runs away).

**Comment by basz** [comment] 2015-04-01 08:33
@oberstet
1. 'lsof -a -p 28290' yields nothing... I don't think the client is keeping connections open. I'm using  Zend\Http\Client in this zendframework module https://github.com/bushbaby/BsbCrossbarPusherStrategy/blob/master/src/Strategy/CrossbarPusherStrategy.php
2. Mostly none. I only have a hack that shows the messages published to the pusher from above library : http://s2.bushbaby.nl:8091
Memory only increases when the publisher is being addressed (which is isn't when my laptop is off/sleeping)

Last thing I noticed, after a restart of the node I see memory is immediate at ~160Mb while you guys are talking about 'stable at ~103MB' after a while. What is a typical usage anyway?

**Comment by oberstet** [comment] 2015-04-01 08:43
@basz You did replace 28290 with the actual PID of the Crossbar.io router worker process running? You can see the PID of the router worker in the log lines ..

**Comment by basz** [comment] 2015-04-01 08:50
@oberstet dumb me https://gist.github.com/basz/522365e92403e1061015

**Comment by oberstet** [comment] 2015-04-01 09:59
@basz there are only 2 TCP FDs .. and those are the listening sockets for your 2 router transports. So neither WAMP clients nor publisher HTTP clients are connected. Mmh. So nothing there also ..

**Comment by hawkowl** [comment] 2015-04-01 12:16
@basz I've pushed out an official 0.10.3 binary release, installable with the instructions from http://crossbar.io/docs/Installation-on-Ubuntu/ and runnable with ```/opt/crossbar/bin/crossbar``. Would you please be able to try that and see if the problem persists?

**Comment by basz** [comment] 2015-04-01 12:37
```
root@s2:~# sudo apt-get update
...
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Ign http://apt.newrelic.com newrelic/non-free Translation-en
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
W: Failed to fetch http://package.crossbar.io/ubuntu/dists/trusty/InRelease  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

```
root@s2:~# curl http://package.crossbar.io/ubuntu/dists/trusty/InRelease
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Origin: Crossbar
Label: Crossbar
Codename: trusty
Date: Wed, 01 Apr 2015 11:33:29 UTC
Architectures: amd64
Components: main
Description: Apt repo for Crossbar
MD5Sum:
 dc7b823f50533478c341f7f6ea38386c 633 main/binary-amd64/Packages
 eb4932abd7912efa57b9b81fe689e25a 431 main/binary-amd64/Packages.gz
 b123f8f79d3bdc137d3a93a61eb90925 104 main/binary-amd64/Release
SHA1:
 8d3b8d413d6df15449d622ce5658d32875a911f2 633 main/binary-amd64/Packages
 215cc21e313c0dce4ce989a66d5ffd2a9ae269f5 431 main/binary-amd64/Packages.gz
 66cce46164e1005ff46477f7aa0ae07d0399445c 104 main/binary-amd64/Release
SHA256:
 7f9bd65a80f514d9bdc80d483e156e6b89cf01d630ce817aa4056a5ef215a350 633 main/binary-amd64/Packages
 f20ad7e4ff104b869a573f361e15ccbd46eef0e5b2c9cc245914da9a7641580c 431 main/binary-amd64/Packages.gz
 a24e15c7d97ba705e0c98f200fbbe27d0334c2a57e41737b41279e09b4ef64df 104 main/binary-amd64/Release
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJVG9eJAAoJEF/GKB/VjGkgG5YIALSdxHNDeNtRhvxjGxOBGOeR
er7aOQpGMBkLmY5itTh/0gg3lguzIFtjuh0IWA9VqGF10AktUq3utGvnQBKwH12D
UsI8OIZJYc3PRfevvfNFBfxz4G1mOtgkv48kvg6S6inV6GbsVdf7+fPHcDXYaE3+
Cp3d05eHFlR8N7KBvkTAsq3ICqvhBBmMlG3oLnJs8AqJueYHr6GI8GaaC+XwVIpl
SbIGxJEBqqNttCtyHou0M6+t1cALcOS9VHLoaldQhvY9fxAze500wIWQoKC+AtSk
Vs94y9mHhX1qeqewkoO76HuZq9ODTCQRoHk7Mv7GC1ksbvBeHf+YoV5Ljcwwf50=
=5VNw
-----END PGP SIGNATURE-----
```

**Comment by basz** [comment] 2015-04-01 12:39
never mind, installs fine. stand by

**Comment by basz** [comment] 2015-04-01 12:47
it's running - now let's see what happens in a hour or so. Fingers crossed (...)

**Comment by basz** [comment] 2015-04-01 13:45
Package does not seem to solve the issue... https://www.dropbox.com/s/tjaogsmmuj5yr4d/Screenshot%202015-04-01%2015.42.29.png?dl=0

I've tried to playing with these values from the config (post_body_limit and timestamp_delta_limit), set them both to zero. Did not help either.

**Comment by basz** [comment] 2015-04-01 13:47
dunno if this is informative to you. 'crossbar version' shows
```
WebSocket UTF8 Validator : ?
WebSocket XOR Masker     : ?
```
while in previous releases the '?' was 'autobahn'.

**Comment by basz** [comment] 2015-04-02 14:40
This morning the pypy (worker) process has exited with a mem footprint of ~750MB. Shouldn't it be restarted automatically?

**Comment by basz** [comment] 2015-04-15 10:19
Problem still exists after apt-get upgrade

```
Crossbar.io                  : 0.10.4

  Autobahn|Python            : 0.10.3
    WebSocket UTF8 Validator : ?
    WebSocket XOR Masker     : ?
    WAMP JSON Codec          : stdlib
    WAMP MsgPack Codec       : msgpack-python-0.4.6
  Twisted                    : 15.1.0-EPollReactor
  Python                     : 2.7.8-PyPy

OS                           : Linux-3.19.1-x86_64-linode53-x86_64-with-debian-jessie-sid
Machine                      : x86_64
```

https://www.dropbox.com/s/2sguq18orqtgqg3/Screenshot%202015-04-15%2012.16.29.png?dl=0

**Comment by Zopieux** [comment] 2015-04-19 14:36
I can observe the same memory leakage with *very low* trafic on latest version. I believe this is a widespread issue in Python programs, it's quite easy to forget the garbage collector isn't magic, you need to take care of "destroying" things you don't need and cleanup datastructures.

**Comment by hawkowl** [comment] 2015-04-19 14:48
@Zopieux have you had any leads as to what specifically causes the memory leak? Something that causes memory leaks in pypy is entirely possible (I fixed one in Twisted only the other day) because the GC semantics are quite different.

I've been sending a lot of traffic through it with little problem in my test cases, so if you have any idea of what specifically causes the memory leak, that'd be very helpful. I'm unable to replicate it using the REST bridge publisher with a few hundred thousand signed requests, so I'd be very happy if you were able to let me know about your configuration. It may have the same underlying cause as @basz but I'm unable to tell without further information.

**Comment by oberstet** [comment] 2015-04-28 07:59
cannot reproduce

**Closed** 2015-04-28 07:59 UTC

**Comment by basz** [comment] 2015-08-19 20:38
I'm sorry to reopen this but I am now (i left crossbar for a while) seeing memory increasing with zero messages passing through it.

It starts with about 190Mb and then it goes up to 220 within 20 minutes.

```
2015-08-19 22:20:37+0200 [Controller  11018] Crossbar.io 0.10.4 starting
2015-08-19 22:20:37+0200 [Controller  11018] Running on PyPy using EPollReactor reactor
2015-08-19 22:20:37+0200 [Controller  11018] Starting from node directory /root/mynode/.crossbar
2015-08-19 22:20:37+0200 [Controller  11018] Starting from local configuration '/root/mynode/.crossbar/config.json'
2015-08-19 22:20:37+0200 [Controller  11018] Warning, could not set process title (setproctitle not installed)
2015-08-19 22:20:37+0200 [Controller  11018] Router created for realm 'crossbar'
2015-08-19 22:20:37+0200 [Controller  11018] No WAMPlets detected in enviroment.
2015-08-19 22:20:37+0200 [Controller  11018] Starting Router with ID 'worker1' ..
2015-08-19 22:20:37+0200 [Controller  11018] Entering reactor event loop ...
2015-08-19 22:20:37+0200 [Router      11035] Log opened.
2015-08-19 22:20:37+0200 [Router      11035] Warning: could not set worker process title (setproctitle not installed)
2015-08-19 22:20:39+0200 [Router      11035] Running under PyPy using EPollReactor reactor
2015-08-19 22:20:40+0200 [Router      11035] Entering event loop ..
2015-08-19 22:20:40+0200 [Controller  11018] Router with ID 'worker1' and PID 11035 started
2015-08-19 22:20:40+0200 [Controller  11018] Router 'worker1': realm 'realm1' (named 'realm1') started
2015-08-19 22:20:40+0200 [Controller  11018] Router 'worker1': role 'role1' (named 'anonymous') started on realm 'realm1'
2015-08-19 22:20:40+0200 [Router      11035] Using default cipher list.
2015-08-19 22:20:40+0200 [Router      11035] Ok, OpenSSL Diffie-Hellman ciphers parameter file loaded.
2015-08-19 22:20:40+0200 [Router      11035] Warning: OpenSSL failed to set ECDH default curve ['module' object has no attribute 'get_elliptic_curve']
2015-08-19 22:20:40+0200 [Router      11035] Site (TLS) starting on 8090
2015-08-19 22:20:40+0200 [Controller  11018] Router 'worker1': transport 'transport1' started
2015-08-19 22:20:40+0200 [Router      11035] Site starting on 8091
2015-08-19 22:20:40+0200 [Controller  11018] Router 'worker1': transport 'transport2' started
```

**Comment by oberstet** [comment] 2015-08-19 20:50
we are not going to reopen this issue (at least now), as we can't reproduce memory running away. we've done extreme stress testing in the testlab and our public demo instance (https://demo.crossbar.io/) runs for long periods (months) without restarts (only restarting when upgrading or changing config).

btw: pls don't run CB or any network server under root.

**Comment by basz** [comment] 2015-08-19 20:56
Hi Tobias ok that's fine - believe you at yr word

however there must be something I can do to help you guys figure out what's going on here... is there more logging i can enable, try it with different settings. It could be my box somehow. but it works fine on other stuff. I could run this setup on a new linode instance for example... just trying to help you (and me, true) out...

**Comment by meejah** [comment] 2015-08-19 21:04
It could be a problem with PyPy -- there as a recent problem on IRC that caused daily re-starts that went away when running under CPython.

Can you try with a CPython, and if your problem goes away I'd been keen to try and understand what's different under PyPy (as I'm sure pypy devs would be too...)

**Comment by basz** [comment] 2015-08-19 21:09
sure, i am under the impression though that I am now running a version from a debian package. Am I able to choose Python with that? I don't think so, but I am kind of a python noob.

**Comment by meejah** [comment] 2015-08-19 21:12
On Debian, you can ``apt-get install pypy pypy-dev virtualenv`` and create a PyPy virtualenv with ``virtualenv --python=pypy my_venv`` and then ``./my_venv/bin/pip install crossbar`` etc...

**Comment by oberstet** [comment] 2015-08-19 21:14
@meejah the CB demo instance runs under PyPy (2.4 on FreeBSD 10.1) and the stress tests we did were running PyPy as well.

@basz I'd recommend our own CB binary packages which include everything: http://crossbar.io/docs/Installation-on-Ubuntu/

**Comment by meejah** [comment] 2015-08-19 21:15
FWIW, I've also been running various tests on Debian + pypy and haven't seen rampant memory-usage.

**Comment by meejah** [comment] 2015-08-19 21:17
@basz If you want to go "bare bones" and install from source/master, please let me know if the documentation is insufficient to tell you how to do that.
