### ISSUE TITLE
file corruption with file upload on certain file sizes

### ISSUE THREAD

**Issue by goeddea** [crossbario/crossbar#590] opened 2016-01-13 11:15 UTC
see https://groups.google.com/forum/#!topic/crossbario/5oxG0RFJeFg - states that files of size greater than 2x chunk size get corrupted.

@markope  - could you take a look at this?

**Comment by singlecheeze** [comment] 2016-01-13 18:34
I think this maybe fixed with the pending patch for twisted filepath FYI

**Comment by markope** [comment] 2016-01-13 19:50
could you share a link to that patch you are refering to?

**Comment by oberstet** [comment] 2016-01-13 20:48
cannot reproduce

**Closed by oberstet** 2016-01-13 20:48 UTC
Labels: bug, needs-investigation
