### ISSUE TITLE
Use u-msgpack-python if msgpack-python not installed

### ISSUE THREAD

**Issue by nj4x** [crossbario/crossbar#419] opened 2015-08-29 04:46 UTC
invalid serialization of WAMP message (unpack(b) received extra data.)
is reported by crossbar.io router when using WampSharp as a client over the MsgpackChannel.

To reproduce:

a) Start crossbar using [.crossbar\config.json](https://gist.github.com/nj4x/13fd21e63f6949aac041)

Tested configuration:

	Crossbar.io package versions and platform information:

	Crossbar.io                  : 0.10.4

	  Autobahn|Python            : 0.10.5.post2
		WebSocket UTF8 Validator : ?
		WebSocket XOR Masker     : ?
		WAMP JSON Codec          : stdlib
		WAMP MsgPack Codec       : msgpack-python-0.4.6
	  Twisted                    : 15.3.0-IOCPReactor
	  Python                     : 2.7.10-CPython

	OS                           : Windows-8-6.2.9200
	Machine                      : AMD64

b) Open [subscriber](https://gist.github.com/nj4x/7b2ec5ebd3068c391258)
c) Run [publisher](https://gist.github.com/nj4x/23076d7cd37c428c0d24)

crossbar log file or console reports

	2015-08-28 22:16:27+0400 [Router       6844] invalid serialization of WAMP message (unpack(b) received extra data.)
	2015-08-28 22:16:33+0400 [Router       6844] invalid serialization of WAMP message (unpack(b) received extra data.)
	2015-08-28 22:16:39+0400 [Router       6844] invalid serialization of WAMP message (unpack(b) received extra data.)

client gets no message on a subscribed topic

I've already opened an [issue](https://github.com/Code-Sharp/WampSharp/issues/94) at [WampSharp](https://github.com/Code-Sharp/WampSharp) and got the following investigations result:

Seems to be an issue with the msgpack-python library which crossbar uses:

	Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import base64
	>>>
	>>> message = "lRDTAAAupj9xtuWAsGNvbS5zaGFycC53YW1wLjGRxIDEgFVx0td5dovKhDQunuX2s
	7Z6G9hPYNlRSJJsYnMX4cxUqP+LXl8g5a1xLDwLrrTccZ7+Ogz+3Nh7IIpFDBQYsqNo2fbmalVWWjUq3
	jSdRZrdkPHVGaa/VssmED7V2tiZWXmYo9S+9QZIp+DW1P6j3tvwaHwiQ5n8qIMrv1oWgX9d"
	>>>
	>>> bytes = base64.b64decode(message)
	>>>
	>>> import msgpack
	>>>
	>>> deserialized = msgpack.unpackb(bytes)
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "msgpack/_unpacker.pyx", line 142, in msgpack._unpacker.unpackb (msgpack/
	_unpacker.cpp:142)
	msgpack.exceptions.ExtraData: unpack(b) received extra data.
	>>>

Seems to work fine with u-msgpack-python library:

	Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import base64
	>>>
	>>> message = "lRDTAAAupj9xtuWAsGNvbS5zaGFycC53YW1wLjGRxIDEgFVx0td5dovKhDQunuX2s
	7Z6G9hPYNlRSJJsYnMX4cxUqP+LXl8g5a1xLDwLrrTccZ7+Ogz+3Nh7IIpFDBQYsqNo2fbmalVWWjUq3
	jSdRZrdkPHVGaa/VssmED7V2tiZWXmYo9S+9QZIp+DW1P6j3tvwaHwiQ5n8qIMrv1oWgX9d"
	>>>
	>>> bytes = base64.b64decode(message)
	>>>
	>>> import umsgpack
	>>>
	>>> deserialized = umsgpack.unpackb(bytes)
	>>>
	>>> deserialized[4]
	['\xc4\x80Uq\xd2\xd7yv\x8b\xca\x844.\x9e\xe5\xf6\xb3\xb6z\x1b\xd8O`\xd9QH\x92lbs
	\x17\xe1\xccT\xa8\xff\x8b^_ \xe5\xadq,<\x0b\xae\xb4\xdcq\x9e\xfe:\x0c\xfe\xdc\xd
	8{ \x8aE\x0c\x14\x18\xb2\xa3h\xd9\xf6\xe6jUVZ5*\xde4\x9dE\x9a\xdd\x90\xf1\xd5\x1
	9\xa6\xbfV\xcb&\x10>\xd5\xda\xd8\x99Yy\x98\xa3\xd4\xbe\xf5\x06H\xa7\xe0\xd6\xd4\
	xfe\xa3\xde\xdb\xf0h|"C\x99\xfc\xa8\x83+\xbfZ\x16\x81']
	>>>

**Comment by oberstet** [comment] 2015-08-30 15:34
Here is what I get using the script from [here](https://github.com/oberstet/scratchbox/tree/master/python/msgpack):

```console
(python279_1)oberstet@thinkpad-t430s:~/scm/scratchbox/python/msgpack$ python test.py 
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    deserialized = umsgpack.unpackb(bytes)
  File "/home/oberstet/python279_1/lib/python2.7/site-packages/umsgpack.py", line 19, in unpackb
    return msgpack.unpackb(buf, **kwargs)
  File "/home/oberstet/python279_1/lib/python2.7/site-packages/msgpack/fallback.py", line 100, in unpackb
    raise ExtraData(ret, unpacker._fb_get_extradata())
msgpack.exceptions.ExtraData: unpack(b) received extra data.
(python279_1)oberstet@thinkpad-t430s:~/scm/scratchbox/python/msgpack$ python test2.py 
Traceback (most recent call last):
  File "test2.py", line 7, in <module>
    deserialized = msgpack.unpackb(bytes)
  File "/home/oberstet/python279_1/lib/python2.7/site-packages/msgpack/fallback.py", line 100, in unpackb
    raise ExtraData(ret, unpacker._fb_get_extradata())
msgpack.exceptions.ExtraData: unpack(b) received extra data.
(python279_1)oberstet@thinkpad-t430s:~/scm/scratchbox/python/msgpack$ 
```

So I have problems reproducing. Then, given there is an issue (which there totally might be), it's probably better addressed to the guys at python-msgpack, as Crossbar.io is just a consumer of that library.

**Comment by darkl** [comment] 2015-08-30 16:23
Hi Tobias,

You couldn't run test.py because you probably installed the wrong package:

You need to install u-msgpack-python and not umsgpack.

```bash
pip uninstall umsgpack
pip install u-msgpack-python
```

I agree an issue should be opened for python-msgpack, but maybe you can consider to replace crossbar implementation to u-msgpack-python instead, or at least making the msgpack serializer pluggable so users can replace the msgpack serializer.

Elad

**Comment by oberstet** [comment] 2015-08-30 16:58
I can reproduce the issue https://github.com/oberstet/scratchbox/tree/master/python/msgpack

This should be resolved at the MsgPack library level.

A first step would be: we could support running on `u-msgpack-python` if `msgpack-python` is missing,

**Comment by darkl** [comment] 2015-08-30 17:21
Ok, investigating it a bit more seems to reveal its actually a bug in my msgpack serialization and in python-msgpack.

You can close this. Sorry about that.

**Comment by oberstet** [comment] 2015-08-30 17:22
np;)

**Closed by oberstet** 2015-08-30 17:22 UTC
Labels: core, enhancement
