### ISSUE TITLE
rlinks: events not forwarded b/w nodes connected to same instance

### ISSUE THREAD

**Issue by asimfarooq5** [crossbario/crossbar#1918] opened 2021-11-26 12:00 UTC
* Instance A connected to instance B
  * forward_local_events: true
  * forward_remote_events: true
  
* Instance C connected to Instance B.
    * forward_local_events: true
    * forward_remote_events: true

Event fired from instance A not published to instance C, also events from Instance C not published to Instance A.

**Comment by om26er** [comment] 2021-11-26 15:23
@asimfarooq5 Can you share the configs that I could use to reproduce that bug

**Comment by asimfarooq5** [comment] 2021-11-26 17:42
{
  "$schema": "https://raw.githubusercontent.com/crossbario/crossbar/master/crossbar.json",
  "version": 2,
  "controller": {
  },
  "workers": [
    {
      "type": "router",
      "realms": [
        {
          "name": "realm1",
          "roles": [
            {
              "name": "anonymous",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                }
              ]
            },
            {
              "name": "router2router",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                }
              ]
            }
          ],
          "rlinks": [
            {
              "id": "edge",
              "realm": "realm1",
              "transport": {
                "type": "rawsocket",
                "endpoint": {
                  "type": "tcp",
                  "host": "localhost",
                  "port": 6688
                },
                "url": "rs://localhost:6688",
                "serializer": "cbor"
              },
              "forward_local_events": true,
              "forward_remote_events": true,
              "forward_local_invocations": false,
              "forward_remote_invocations": false
            }
          ]
        }
      ],
      "transports": [
        {
          "type": "rawsocket",
          "endpoint": {
            "type": "tcp",
            "port": 5588,
            "backlog": 1024
          },
          "options": {
            "max_message_size": 1048576
          },
          "serializers": [
            "cbor",
            "msgpack",
            "json"
          ]
        },
        {
          "type": "web",
          "endpoint": {
            "type": "tcp",
            "port": 8080,
            "backlog": 1024
          },
          "paths": {
            "ws": {
              "type": "websocket",
              "serializers": [
                "cbor",
                "msgpack",
                "json"
              ]
            }
          }
        }
      ]
    },
    {
      "type": "router",
      "realms": [
        {
          "name": "realm1",
          "roles": [
            {
              "name": "anonymous",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                }
              ]
            },
            {
              "name": "router2router",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                }
              ]
            }
          ],
          "rlinks": [
            {
              "id": "cloud_1",
              "realm": "realm1",
              "transport": {
                "type": "rawsocket",
                "endpoint": {
                  "type": "tcp",
                  "host": "localhost",
                  "port": 7788
                },
                "url": "rs://localhost:7788",
                "serializer": "cbor"
              },
              "forward_local_events": true,
              "forward_remote_events": true,
              "forward_local_invocations": false,
              "forward_remote_invocations": false
            }
          ]
        }
      ],
      "transports": [
        {
          "type": "rawsocket",
          "endpoint": {
            "type": "tcp",
            "port": 6688,
            "backlog": 1024
          },
          "options": {
            "max_message_size": 1048576
          },
          "serializers": [
            "cbor",
            "msgpack",
            "json"
          ],
          "auth": {
            "cryptosign": {
              "type": "static",
              "principals": {
                "edge": {
                  "realm": "realm1",
                  "role": "router2router",
                  "authorized_keys": [
                    "420b529d50db39dd49948bb878e51defc150f7fc3378964520bb0db74d44356"
                  ]
                },
                "cloud_2": {
                  "realm": "realm1",
                  "role": "router2router",
                  "authorized_keys": [
                    "420b529d50db39dd49948bb878e51defc150f7fc3378964520bb0db74d44356d"
                  ]
                }
              }
            }
          }
        },
        {
          "type": "web",
          "endpoint": {
            "type": "tcp",
            "port": 8081,
            "backlog": 1024
          },
          "paths": {
            "ws": {
              "type": "websocket",
              "serializers": [
                "cbor",
                "msgpack",
                "json"
              ]
            }
          }
        }
      ]
    },
    {
      "type": "router",
      "realms": [
        {
          "name": "realm1",
          "roles": [
            {
              "name": "anonymous",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                }
              ]
            },
            {
              "name": "router2router",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                }
              ]
            }
          ],
          "rlinks": [
            {
              "id": "cloud_2",
              "realm": "realm1",
              "transport": {
                "type": "rawsocket",
                "endpoint": {
                  "type": "tcp",
                  "host": "localhost",
                  "port": 6688
                },
                "url": "rs://localhost:6688",
                "serializer": "cbor"
              },
              "forward_local_events": true,
              "forward_remote_events": true,
              "forward_local_invocations": false,
              "forward_remote_invocations": false
            }
          ]
        }
      ],
      "transports": [
        {
          "type": "rawsocket",
          "endpoint": {
            "type": "tcp",
            "port": 7788,
            "backlog": 1024
          },
          "options": {
            "max_message_size": 1048576
          },
          "serializers": [
            "cbor",
            "msgpack",
            "json"
          ],
          "auth": {
            "cryptosign": {
              "type": "static",
              "principals": {
                "cloud_1": {
                  "realm": "realm1",
                  "role": "router2router",
                  "authorized_keys": [
                    "420b529d50db39dd49948bb878e51defc150f7fc3378964520bb0db74d44356d"
                  ]
                }
              }
            }
          }
        },
        {
          "type": "web",
          "endpoint": {
            "type": "tcp",
            "port": 8082,
            "backlog": 1024
          },
          "paths": {
            "ws": {
              "type": "websocket",
              "serializers": [
                "cbor",
                "msgpack",
                "json"
              ]
            }
          }
        }
      ]
    }
  ]
}

**Comment by asimfarooq5** [comment] 2021-11-26 17:44
```
{
  "$schema": "https://raw.githubusercontent.com/crossbario/crossbar/master/crossbar.json",
  "version": 2,
  "controller": {
  },
  "workers": [
    {
      "type": "router",
      "realms": [
        {
          "name": "realm1",
          "roles": [
            {
              "name": "anonymous",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                }
              ]
            },
            {
              "name": "router2router",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                }
              ]
            }
          ],
          "rlinks": [
            {
              "id": "edge",
              "realm": "realm1",
              "transport": {
                "type": "rawsocket",
                "endpoint": {
                  "type": "tcp",
                  "host": "localhost",
                  "port": 6688
                },
                "url": "rs://localhost:6688",
                "serializer": "cbor"
              },
              "forward_local_events": true,
              "forward_remote_events": true,
              "forward_local_invocations": false,
              "forward_remote_invocations": false
            }
          ]
        }
      ],
      "transports": [
        {
          "type": "rawsocket",
          "endpoint": {
            "type": "tcp",
            "port": 5588,
            "backlog": 1024
          },
          "options": {
            "max_message_size": 1048576
          },
          "serializers": [
            "cbor",
            "msgpack",
            "json"
          ]
        },
        {
          "type": "web",
          "endpoint": {
            "type": "tcp",
            "port": 8080,
            "backlog": 1024
          },
          "paths": {
            "ws": {
              "type": "websocket",
              "serializers": [
                "cbor",
                "msgpack",
                "json"
              ]
            }
          }
        }
      ]
    },
    {
      "type": "router",
      "realms": [
        {
          "name": "realm1",
          "roles": [
            {
              "name": "anonymous",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                }
              ]
            },
            {
              "name": "router2router",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                }
              ]
            }
          ],
          "rlinks": [
            {
              "id": "cloud_1",
              "realm": "realm1",
              "transport": {
                "type": "rawsocket",
                "endpoint": {
                  "type": "tcp",
                  "host": "localhost",
                  "port": 7788
                },
                "url": "rs://localhost:7788",
                "serializer": "cbor"
              },
              "forward_local_events": true,
              "forward_remote_events": true,
              "forward_local_invocations": false,
              "forward_remote_invocations": false
            }
          ]
        }
      ],
      "transports": [
        {
          "type": "rawsocket",
          "endpoint": {
            "type": "tcp",
            "port": 6688,
            "backlog": 1024
          },
          "options": {
            "max_message_size": 1048576
          },
          "serializers": [
            "cbor",
            "msgpack",
            "json"
          ],
          "auth": {
            "cryptosign": {
              "type": "static",
              "principals": {
                "edge": {
                  "realm": "realm1",
                  "role": "router2router",
                  "authorized_keys": [
                    "420b529d50db39dd49948bb878e51defc150f7fc3378964520bb0db74d44356"
                  ]
                },
                "cloud_2": {
                  "realm": "realm1",
                  "role": "router2router",
                  "authorized_keys": [
                    "420b529d50db39dd49948bb878e51defc150f7fc3378964520bb0db74d44356d"
                  ]
                }
              }
            }
          }
        },
        {
          "type": "web",
          "endpoint": {
            "type": "tcp",
            "port": 8081,
            "backlog": 1024
          },
          "paths": {
            "ws": {
              "type": "websocket",
              "serializers": [
                "cbor",
                "msgpack",
                "json"
              ]
            }
          }
        }
      ]
    },
    {
      "type": "router",
      "realms": [
        {
          "name": "realm1",
          "roles": [
            {
              "name": "anonymous",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                }
              ]
            },
            {
              "name": "router2router",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": true,
                    "publisher": true
                  },
                  "cache": true
                }
              ]
            }
          ],
          "rlinks": [
            {
              "id": "cloud_2",
              "realm": "realm1",
              "transport": {
                "type": "rawsocket",
                "endpoint": {
                  "type": "tcp",
                  "host": "localhost",
                  "port": 6688
                },
                "url": "rs://localhost:6688",
                "serializer": "cbor"
              },
              "forward_local_events": true,
              "forward_remote_events": true,
              "forward_local_invocations": false,
              "forward_remote_invocations": false
            }
          ]
        }
      ],
      "transports": [
        {
          "type": "rawsocket",
          "endpoint": {
            "type": "tcp",
            "port": 7788,
            "backlog": 1024
          },
          "options": {
            "max_message_size": 1048576
          },
          "serializers": [
            "cbor",
            "msgpack",
            "json"
          ],
          "auth": {
            "cryptosign": {
              "type": "static",
              "principals": {
                "cloud_1": {
                  "realm": "realm1",
                  "role": "router2router",
                  "authorized_keys": [
                    "420b529d50db39dd49948bb878e51defc150f7fc3378964520bb0db74d44356d"
                  ]
                }
              }
            }
          }
        },
        {
          "type": "web",
          "endpoint": {
            "type": "tcp",
            "port": 8082,
            "backlog": 1024
          },
          "paths": {
            "ws": {
              "type": "websocket",
              "serializers": [
                "cbor",
                "msgpack",
                "json"
              ]
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by om26er** [comment] 2021-11-26 20:43
It's probably useful to have separate configs for each node. However I am able to reproduce the issue with the provided config as well.

**Comment by om26er** [comment] 2021-11-26 22:02
Here is the basic outline of rlink structure that is reported in the issue

INSTANCE A --------> INSTANCE B <-------- INSTANCE C

An event published by a client connected to instance A is correctly received on Instance B but NOT on a client connected to instance C (and vice versa).

@oberstet What are your thoughts on this, do you think it's worked as intended or is that a bug ?

**Comment by oberstet** [comment] 2021-11-27 06:30
@om26er this network topology is different from a full mesh, but it is relevant. here is why we want to test both:

1. a full mesh of nodes (with rlinks between any two nodes in the mesh .. that is, at least one undirectional rlink between two nodes) replicates the topology we want to use for **"clustering"** - that is HA and scale-out within a data-center (eg within a AWS region spanning AZs in that region)
2. a tree like topology, which is what @asimfarooq5 created in minimal form (node B is the tree root, nodes A/C are leaf nodes) replicates the topology we want to use for **"edge-cloud"** - that is a single node or a full mesh of nodes running in the cloud, and edge nodes running on uplinks with NAT/Firewall restrictions

The design of rlinks was created with both of above specific scenarios in mind, though it should generally be able to cover many more scenarios with different topologies.

Finally, but that is still not yet fully implemented, we want to cover scenarios where the topology spans multiple different node operators / owners, aka **"federation"**.

----

Having said that, the code and design contains the following to make above possible:

1. knobs forward_local_events/forward_remote_events/forward_local_invocations/forward_remote_invocations to control if an rlink A=>B will replicate local (node A) publications/registrations on the remote side (node B), and vice versa
2. this is because between two nodes A and B there could be 2 unidirectional rlinks, A=>B and B=>A
3. every WAMP message for a publish/registration that is forwarded from a node A over an rlink to a remote node B will have "node A" appended to the `forward_for` list of nodes - this list effectively carries the set and the route a forwarded WAMP message has taken through the rlink-connected network of nodes

**Comment by oberstet** [comment] 2021-11-27 06:44
eg `REGISTER.options.forward_for` is a `dict` with `session`, `authid` and `authrole`

https://github.com/crossbario/autobahn-python/blob/9de497273c6db50d8697019844f6a7fd3a867789/autobahn/wamp/message.py#L4808
https://github.com/crossbario/autobahn-python/blob/9de497273c6db50d8697019844f6a7fd3a867789/autobahn/wamp/message.py#L4846

and for `PUBLISH`

https://github.com/crossbario/autobahn-python/blob/9de497273c6db50d8697019844f6a7fd3a867789/autobahn/wamp/message.py#L2517
https://github.com/crossbario/autobahn-python/blob/9de497273c6db50d8697019844f6a7fd3a867789/autobahn/wamp/message.py#L2587

this is then used in CB here: https://gist.github.com/oberstet/d270630c3f635ed27f986d0101a5b817

**Comment by om26er** [comment] 2021-12-11 22:22
I investigated into this. It seems the message does arrive, however the router eats it here https://github.com/crossbario/crossbar/blob/c5184c74d9bc23a1f1f51bee72c9b954ea701fef/crossbar/worker/rlink.py#L117

Which causes the "local leg" to not receive the event, removing that return statement fixes the issue.

Thinking a bit more about it, I believe the above condition tries to avoid duplicate forwarding of events among different nodes

**Comment by om26er** [comment] 2021-12-12 19:44
@oberstet what are your thoughts on the above ? We obviously don't want redundant event forwarding but at the same time need to support the above topology as well.

**Comment by oberstet** [comment] 2021-12-12 21:59
@om26er we should first create an automated test that demonstrates the bug

**Comment by oberstet** [comment] 2021-12-12 23:07
> "the event comes already forwarded from a router node"

I actually don't understand why this is handled in rlink.py, and not in the router files.

forward_for is supposed to work like this:

* the originating node (eg the one a caller is connected to) starts the list with it's own node-id/session
* when a message is forwarded over an rlink, the node forwarded to is appended to the list
* when an outgoing message is to be distributed over rlinks connected, target nodes already contained in forward_for are skipped

this should ensure that messages forwarded flood the network, but don't loop back to previous nodes ..

**Comment by oberstet** [comment] 2022-03-31 03:31
closing - can't reproduce (no CI test to demonstrate)

**Closed by oberstet** 2022-03-31 03:31 UTC
Labels: bug, needs-discussion
