### ISSUE TITLE
Cannot start crossbar with Python 3.5.0

### ISSUE THREAD

**Issue by omnibrain** [crossbario/crossbar#488] opened 2015-10-21 15:26 UTC
I'm having trouble starting Crossbar with Python 3.5 on Arch Linux (4.1.6-1). Full stack trace:

```
2015-10-21T18:14:04+0200 [Controller  10698] Automatically choosing optimal Twisted reactor
2015-10-21T18:14:04+0200 [Controller  10698] Running on Linux and optimal reactor (epoll) was installed.
2015-10-21T18:14:04+0200 [Controller  10698]      __  __  __  __  __  __      __     __
2015-10-21T18:14:04+0200 [Controller  10698]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2015-10-21T18:14:04+0200 [Controller  10698]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2015-10-21T18:14:04+0200 [Controller  10698]                                         
2015-10-21T18:14:04+0200 [Controller  10698]     Version: 0.11.1     
2015-10-21T18:14:04+0200 [Controller  10698] 
2015-10-21T18:14:04+0200 [Controller  10698] Starting from node directory /home/rvoellmy/projects/data-provision-system/.crossbar
2015-10-21T18:14:04+0200 [Controller  10698] Loading node configuration file '/home/rvoellmy/projects/data-provision-system/.crossbar/config.json'
2015-10-21T18:14:04+0200 [Controller  10698] Entering reactor event loop...
2015-10-21T18:14:04+0200 [Controller  10698] Warning, could not set process title (setproctitle not installed)
2015-10-21T18:14:04+0200 [Controller  10698] Process utilities not available
2015-10-21T18:14:04+0200 [Controller  10698] Joined realm 'crossbar' on node management router
2015-10-21T18:14:05+0200 [Controller  10698] No WAMPlets detected in enviroment.
2015-10-21T18:14:05+0200 [Controller  10698] Starting Router with ID 'worker1'...
2015-10-21T18:14:05+0200 [Controller  10698] Interal error: connection to forked native worker failed ([Failure instance: Traceback: <class 'TypeError'>: Environment contains a non-string value
/usr/lib/python3.5/site-packages/twisted/internet/defer.py:1128:_inlineCallbacks
/usr/lib/python3.5/site-packages/crossbar/controller/node.py:280:_startup
/usr/lib/python3.5/site-packages/crossbar/controller/process.py:288:start_router
/usr/lib/python3.5/site-packages/crossbar/controller/process.py:523:_start_native_worker
--- <exception caught here> ---
/usr/lib/python3.5/site-packages/crossbar/twisted/processutil.py:110:connect
/usr/lib/python3.5/site-packages/twisted/internet/posixbase.py:331:spawnProcess
/usr/lib/python3.5/site-packages/twisted/internet/base.py:925:_checkProcessArgs
])
2015-10-21T18:14:05+0200 [Controller  10698] Failed to start native worker: Environment contains a non-string value
2015-10-21T18:14:05+0200 [Controller  10698] Failed to start native worker: Environment contains a non-string value
2015-10-21T18:14:05+0200 [Controller  10698] Main loop terminated.
```

I'm trying to start crossbar using the default config.json file that is generated by ```crossbar init```.

Output of ```crossbar version```:

```
 Crossbar.io        : 0.11.1
   Autobahn         : 0.10.9
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : -
   Twisted          : 15.4.0-EPollReactor
   Python           : 3.5.0/CPython
 OS                 : Linux-4.2.2-1-ARCH-x86_64-with-arch
 Machine            : x86_64
```

Not sure if this is a twisted or crossbar issue. Any help is greatly appreciated.

**Comment by oberstet** [comment] 2015-10-21 16:01
Could you attach your node config and the environment variables you set?

**Comment by omnibrain** [comment] 2015-10-21 16:03
I didn't set any environment variables. The node config is the default config that is generated from ```crossbar init```:

```json
{
   "controller": {
   },
   "workers": [
      {
         "type": "router",
         "realms": [
            {
               "name": "realm1",
               "roles": [
                  {
                     "name": "anonymous",
                     "permissions": [
                        {
                           "uri": "*",
                           "publish": true,
                           "subscribe": true,
                           "call": true,
                           "register": true
                        }
                     ]
                  }
               ]
            }
         ],
         "transports": [
            {
               "type": "web",
               "endpoint": {
                  "type": "tcp",
                  "port": 8080
               },
               "paths": {
                  "/": {
                     "type": "static",
                     "directory": ".."
                  },
                  "ws": {
                     "type": "websocket"
                  }
               }
            }
         ]
      }
   ]
}
```

**Comment by oberstet** [comment] 2015-10-21 16:09
@hawkowl `unicode` isn't a thing in py3? https://github.com/twisted/twisted/blob/trunk/twisted/internet/base.py#L889

**Comment by oberstet** [comment] 2015-10-21 16:14
There might also be something here

* https://github.com/crossbario/crossbar/blob/master/crossbar/controller/process.py#L380
* https://github.com/crossbario/crossbar/blob/master/crossbar/controller/process.py#L385

**Comment by hawkowl** [comment] 2015-10-22 03:11
@oberstet we import `unicode` from `twisted.python.compat`, and it's a alias to `str` on Py3.

I'll investigate this one.

@omnibrain could you try Python 3.4 for now? Twisted doesn't support 3.5 until the next release (this month I think -- the supporting patches have landed in `trunk`), and Travis only just got 3.5 support so we haven't run Crossbar, Autobahn, or txaio on it yet, meaning things like this can happen.

**Comment by singlecheeze** [comment] 2015-11-03 02:02
I'm successfully running crossbar in py 3.5 and additionally using async/await without any issues....
```text
Automatically choosing optimal Twisted reactor
Running on Linux and optimal reactor (epoll) was installed.
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
                                        
 Crossbar.io        : 0.11.1
   Autobahn         : 0.10.9
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : -
   Twisted          : 15.4.0-EPollReactor
   Python           : 3.5.0/CPython
 OS                 : Linux-3.19.0-28-generic-x86_64-with-debian-jessie-sid
 Machine            : x86_64
```

**Comment by singlecheeze** [comment] 2015-11-03 02:09
Just got a few more errors when trying to drag 2 ~600 MB files into the dropzone on the example upload page... I'm wondering if the issue is related to a non-async open/write it looks like the router is doing (I wish python had builtin libs for async file read/write)?

```text
2015-11-02T21:04:39-0500 [Router       8402] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1445, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1703, in _finishRequestBody
    self.allContentReceived()
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1766, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 832, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/site-packages/crossbar/twisted/resource.py", line 365, in render_POST
    with open(_chunkName.path, 'wb') as chunk:
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/dave/monocle/frontend/temp/a5UA0000000L1sFMAS~1~DublinXIO-vbxbcl01psdu_2015_10_23_1039.tar.gz/#kfhfkzuru578e38viokbjhfvz4w__chunk_4'

2015-11-02T21:06:29-0500 [Router       8402] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1445, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1703, in _finishRequestBody
    self.allContentReceived()
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1766, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 832, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/site-packages/crossbar/twisted/resource.py", line 365, in render_POST
    with open(_chunkName.path, 'wb') as chunk:
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/dave/monocle/frontend/temp/a5UA0000000L1sFMAS~1~DublinXIO-vbxbcl01psdu_2015_10_23_1039.tar.gz/#kfhfkzuru578e38viokbjhfvz4w__chunk_4'

2015-11-02T21:06:29-0500 [Router       8402] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1445, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1703, in _finishRequestBody
    self.allContentReceived()
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1766, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 832, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/site-packages/crossbar/twisted/resource.py", line 365, in render_POST
    with open(_chunkName.path, 'wb') as chunk:
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/dave/monocle/frontend/temp/a5UA0000000L1sFMAS~1~DublinXIO-vbxbcl01psdu_2015_10_23_1039.tar.gz/#kfhfkzuru578e38viokbjhfvz4w__chunk_5'

2015-11-02T21:06:29-0500 [Router       8402] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1445, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1703, in _finishRequestBody
    self.allContentReceived()
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1766, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 832, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/site-packages/crossbar/twisted/resource.py", line 365, in render_POST
    with open(_chunkName.path, 'wb') as chunk:
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/dave/monocle/frontend/temp/a5UA0000000L1sFMAS~1~DublinXIO-vbxbcl01psdu_2015_10_23_1039.tar.gz/#kfhfkzuru578e38viokbjhfvz4w__chunk_6'
```

**Comment by oberstet** [comment] 2016-01-25 16:53
cannot reproduce (tested with CPy 3.5.1)

**Comment by FirefighterBlu3** [comment] 2016-05-04 06:46
this can happen if the shell PS1 is exotic. i modified the exception raised to print the key affected:

```log
2016-05-04T06:36:50+0000 [Controller   7698] Failed to start native worker: Environment[b'PS1'] contains a non-string value: None
```
```bash
┌[✓ non-root@reeferboy [/etc/nginx/sites/reeferboy.blue-labs.org/api]
└─> echo $PS1
\n\[\e[36m\]┌\[\e[36m\][\[\033[01;37m\]$(if [[ $? == 0 ]]; then echo "\[\033[01;32m\]\342\234\223"; else echo "\[\033[01;31m\]\342\234\227"; fi) \[\033[01;31m\]\u@\h\[\033[01;34m\] [\w]\[\033[00m\]\n\[\e[36m\]└─>\[\e[0m\]
```

**Comment by meejah** [comment] 2016-05-04 20:34
@FirefighterBlu3 I tried with that very ``PS1`` on Debian jessie with Python 3.4.2 and Python 3.5.1 and a simple do-nothing guest component which launched fine -- what OS are you on?

**Closed by meejah** 2016-05-04 20:34 UTC
Labels: bug, needs-investigation, Python 3

**Comment by meejah** [comment] 2016-05-04 20:44
Possibly-useful: what does "print(sys.getdefaultencoding())" from a Python3 interpreter print out for @FirefighterBlu3  and @omnibrain

**Comment by FirefighterBlu3** [comment] 2016-05-04 23:10
my actual PS is:

```bash
export PS1="\n\[\e[36m\]┌\[\e[36m\][\[\033[01;37m\]\$(if [[ \$? == 0 ]]; then echo \"\[\033[01;32m\]\342\234\223\"; else echo \"\[\033[01;31m\]\342\234\227\"; fi) $(if [[ ${EUID} == 0 ]]; then echo '\[\033[01;31m\]\u@\h'; else echo '\[\033[01;32m\]\u@\h'; fi)\[\033[01;34m\] [\w]\[\033[00m\]\n\[\e[36m\]└─>\[\e[0m\] "
```

i can do PS1="foo" crossbar start and it'll run fine.

```python
>>> print(sys.getdefaultencoding())
utf-8
```

**Comment by meejah** [comment] 2016-05-05 19:16
@FirefighterBlu3 Hmm, any other hints? I tried with that very PS1 and I works for me. I'm using ``bash`` inside an ``rxvt-unicode-256color`` terminal...
