### ISSUE TITLE
Reverse proxy web service

### ISSUE THREAD

**Issue by taion** [crossbario/crossbar#390] opened 2015-08-16 17:11 UTC
Would it make sense for there to be a reverse proxy web service? Given that there are already a bunch of others for serving all sorts of web assets like statics for development configurations, it seems like it might make sense to have something that sets up a `ReverseProxyResource`.

**Comment by oberstet** [comment] 2015-08-19 20:40
I am feeling ambivalent about this in general: on the one hand, it's convenient that Crossbar.io now comes with batteries included rgd Web stuff in general. On the other hand, it's a departure from the core functionality of Crossbar.io: WAMP routing. And: it doesn't make sense trying to compete with say Nginx. Lost cause. Mmh.

**Comment by meejah** [comment] 2015-08-19 20:55
If ``twisted.web.proxy.ReverseProxyResource`` doesn't work for your use-case, perhaps Twisted would be interested in a patch/bug-report?

**Comment by oberstet** [comment] 2015-08-19 21:17
oh cool, I wasn't aware of https://twistedmatrix.com/documents/current/api/twisted.web.proxy.ReverseProxyResource.html

Well, it would be trivial to add that to Crossbar.io. As mentioned above, my main itch is that I feel ambivalent about adding more and more bells and whistles to CB that are "non-core" (not WAMP routing related)

**Comment by taion** [comment] 2015-08-19 21:23
`ReverseProxyResource` works. It's mostly possible with the `resource` "Generic Twisted Web resource" support, except the `extra` config gets doesn't get passed through as `**kwargs`, and the `ReverseProxyResource` itself chokes on some Unicode stuff when I tried it on Python 2.

I ended up writing a very quick and dirty reverse proxy as a WSGI app (only had to proxy one endpoint with one method), and I'm going to be moving all this HTTP routing stuff to Nginx sooner or later.

I understand not wanting to introduce extra stuff to Crossbar, but the lack of a basic reverse proxy (especially given the presence of `ReverseProxyResource` that will do most of the work) strikes me as a conspicuous absence given the presence of the `static` and `wsgi` resources.

**Comment by oberstet** [comment] 2015-08-19 21:32
> ... strikes me as a conspicuous absence given the presence of the static and wsgi resources.

Fair enough. Yes, I guess we already "crossed the line" with wsgi at the latest.

Alright. I am fine making this a feature request then. 

What we should _also_ do is: make a clear statement in the CB docs what's a core feature, and what should be considered "extra". The extras are goodies that come with the current implementation line of CB, but users should be discouraged from creating hard dependencies in their applications on those.

**Comment by taion** [comment] 2015-08-19 21:41
Makes sense to me - these features are very convenient for development for things centered on Crossbar's routing, but would be inadvisable to use in a deployed, production configuration.

**Comment by shaworth** [comment] 2015-08-19 21:42
All the discouragement in the world won't prevent the hard dependencies.
Once you introduce a feature, you are generally stuck with it.

Given that reverse proxies are readily available and are difficult to do
'simple' I would advise against this particular branch of feature creep.
The 'enterprise' solution is robust documentation and examples of how to
successfully deploy crossbar behind the heavy lifters in the reverse proxy
ecosystem.

My advise is to keep focused on crossbar / WAMP.  There is nothing else
like it.

**Comment by taion** [comment] 2015-08-19 21:48
@shaworth 

So are WSGI web servers, and servers for static assets - but they're really helpful DX-wise for getting something simple started - I don't want to have to set up Nginx routing for trivial projects.

Maybe some sort of opt-in `--development` flag, without which the "extras" won't work?

**Comment by oberstet** [comment] 2015-08-19 22:05
@shaworth From your comment, I guess I share your mindset.

Stuff like static Web serving or reverse proxying is a solved problem. Using Nginx, S3 or some CDN is generally the way to go in production.

But it's also true that those things come in handy when doing development (or when you just don't need CDN scale).

Rgd feature creep: don't worry. The core routing is in and will stay in focus. There is enough in the pipeline to make that even more awesome.

Rgd. this specific feature request: if there wouldn't be a Twisted Web resource already in Twisted for reverse proxying, I'd reject the feature right away. I haven't used it myself, but Twisted stuff is almost always high quality (which doesn't necessarily mean on-par feature wise with Nginx eg of course). And the code required to make that available within CB is like 30 lines of code. Of course that isn't the main question, but it's a necessary precondition in my view. CB wouldn't start developing a reverse proxy code from scratch. That would be definitely over the top.

@taion `--development` switch: interesting idea. Or starting the log with a big "WARNING: use of extra feature X is generally discourage other than for dev" or something.

**Comment by taion** [comment] 2015-08-19 22:21
The nice thing with an explicit opt-in switch is that it requires deliberate effort from the developer to enable. Even the loudest warnings can be ignored - and they can be unhelpful/noisy when running in development mode.

**Comment by shaworth** [comment] 2015-08-20 03:24
@Jimmy all valid points.  No disputing that ease of adoption generates mind
share.

I really wish I had the time to package an entire 'WAMP ready' dev stack.
Something like Apache 2 + Reddis/CouchDB + crossbar.io.  Alas, too little
time.

@Tobias although there are valid arguments both ways I agree with a set of
clear and concise objectives.

**Comment by taion** [comment] 2015-08-20 03:37
@shaworth 

One analogy here is that, in production, you should never use e.g. Flask's built-in web server,  or Django `manage.py runserver` - certainly you shouldn't serve static assets from either, but it'd be awfully painful to develop for either without that functionality.

It's not lack of ability that stops people from using Nginx + uWSGI or something in those cases. Developer experience is important all-around.

**Comment by oberstet** [comment] 2015-08-24 16:42
closing as duplicate of https://github.com/crossbario/crossbar/issues/390

**Closed by oberstet** 2015-08-24 16:42 UTC
Labels: enhancement
